tasks:
  - init: mkdir build build-dbg && cmake -S . -B build -D CMAKE_BUILD_TYPE=Release && cmake -S . -B build-dbg -D CMAKE_BUILD_TYPE=Debug
  # Required for shell linting
  - init: brew install shellcheck
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
    - medo64.render-crlf@1.5.3:HLx6qIeeDMkxZSYLpmfjnw==
    - exiasr.hadolint@0.3.0:/FkAW3eTb+z9O7VZAyAa0w==