# Toplevel Makefile for Linux build of PasswordSafe

all clean debug release unicodedebug unicoderelease:
	$(MAKE) -C src/os/linux $@
	$(MAKE) -C src/corelib $@
	$(MAKE) -C src/ui/wxWidgets $@

.PHONY:	all clean
# Local variables:
# mode: makefile
# End:
