//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PasswordSafe.rc
//
#define IDR_ACCS                        100
#define IDR_MAINFRAME                   101
#define IDR_MAINMENU                    102
#define IDD_ABOUTBOX                    110
#define IDD_ADD                         111
#define IDD_ADVANCED                    112
#define IDD_ADVANCEDMERGE               113
#define IDD_COLUMNCHOOSER               114
#define IDD_COMPARE_RESULTS             115
#define IDD_CONFIRMDELETE_DIALOG        116
#define IDD_CREATE_SHORTCUT             117
#define IDD_CRYPTKEYENTRY               118
#define IDD_DISPLAY_EXPIRED_ENTRIES     119
#define IDD_DLG_PWHIST                  120
#define IDD_EDIT                        121
#define IDD_EDIT_SHORTCUT               122
#define IDD_EXPORT_TEXT                 123
#define IDD_EXPORT_XML                  124
#define IDD_IMPORT_TEXT                 125
#define IDD_IMPORT_XML                  126
#define IDD_KEYCHANGE_DIALOG            127
#define IDD_MINIMIZECLEAR_DIALOG        128
#define IDD_OPTIONS                     129
#define IDD_PASSKEYENTRY                130
#define IDD_PASSKEYENTRY_FIRST          131
#define IDD_PASSKEYENTRY_WITHEXIT       132
#define IDD_PASSKEYSETUP                133
#define IDD_PASSWORDSAFE_DIALOG         134
#define IDD_PICKEXPDATETIME             135
#define IDD_PROPERTIES                  136
#define IDD_PS_BACKUP                   137
#define IDD_PS_DISPLAY                  138
#define IDD_PS_MISC                     139
#define IDD_PS_PASSWORDHISTORY          140
#define IDD_PS_PASSWORDPOLICY           141
#define IDD_PS_SECURITY                 142
#define IDD_PS_SYSTEM                   143
#define IDD_QUERYSETDEF                 144
#define IDD_SECURECLEAR                 145
#define IDD_TRYAGAIN                    146
#define IDD_USERNAMEENTRY               147
#define IDD_PWFONTDIALOG                148
#define IDR_POPCOLUMNS                  160
#define IDR_POPCOPYTOCOMPARISON         161
#define IDR_POPCOPYTOORIGINAL           162
#define IDR_POPCUSTOMIZETOOLBAR         163
#define IDR_POPGROUP                    164
#define IDR_POPMENU                     165
#define IDR_POPTRAY                     166
#define IDR_POPTREE                     167
#define IDR_POPRIGHTDRAG                168
#define IDI_CORNERICON                  180
#define IDI_LOCKEDICON                  181
#define IDI_MBASKICON                   182
#define IDI_MBINFOICON                  183
#define IDI_MBSTOPICON                  184
#define IDI_MBWARNICON                  185
#define IDI_ALIAS                       186
#define IDI_ABASE                       187
#define IDI_ABASE_EXPIRED               188
#define IDI_ABASE_WARNEXPIRED           189
#define IDI_NORMAL                      190
#define IDI_NORMAL_EXPIRED              191
#define IDI_NORMAL_WARNEXPIRED          192
#define IDI_SBASE                       193
#define IDI_SBASE_EXPIRED               194
#define IDI_SBASE_WARNEXPIRED           195
#define IDI_SHORTCUT                    196
#define IDI_TRAY                        205
#define IDI_TRAY_BLUE                   206
#define IDI_TRAY_WHITE                  207
#define IDI_TRAY_YELLOW                 208
#define IDI_UNLOCKEDICON                209
#define IDB_CLOGO                       220
#define IDB_CLOGO_SMALL                 221
#define IDB_CTEXT                       222
#define IDB_PSLOGO                      223
#define IDB_PWSDB                       224
#define IDB_ALIAS                       230
#define IDB_ABASE                       231
#define IDB_ABASE_EXPIRED               232
#define IDB_ABASE_WARNEXPIRED           233
#define IDB_NODE                        234
#define IDB_NORMAL                      235
#define IDB_NORMAL_EXPIRED              236
#define IDB_NORMAL_WARNEXPIRED          237
#define IDB_SHORTCUT                    238
#define IDB_SBASE                       239
#define IDB_SBASE_EXPIRED               240
#define IDB_SBASE_WARNEXPIRED           241
#define IDB_FINDADVANCED_CLASSIC        250
#define IDB_FINDADVANCED_NEW            251
#define IDB_FINDCASE_I_CLASSIC          252
#define IDB_FINDCASE_I_NEW              253
#define IDB_FINDCASE_S_CLASSIC          254
#define IDB_FINDCASE_S_NEW              255
#define IDB_FINDCLEAR_CLASSIC           256
#define IDB_FINDCLEAR_NEW               257
#define IDB_FINDCLOSE_CLASSIC           258
#define IDB_FINDCLOSE_NEW               259
#define IDB_FINDREPORT_CLASSIC          260
#define IDB_FINDREPORT_NEW              261
#define IDB_FINDCTRLPLACEHOLDER         262
#define IDB_ABOUT_CLASSIC               280
#define IDB_ABOUT_NEW                   281
#define IDB_ABOUT_NEW_D                 282
#define IDB_ADD_CLASSIC                 283
#define IDB_ADD_NEW                     284
#define IDB_ADD_NEW_D                   285
#define IDB_AUTOTYPE_CLASSIC            286
#define IDB_AUTOTYPE_NEW                287
#define IDB_AUTOTYPE_NEW_D              288
#define IDB_BACKUPSAFE_CLASSIC          289
#define IDB_BACKUPSAFE_NEW              290
#define IDB_BACKUPSAFE_NEW_D            291
#define IDB_BROWSEURL_CLASSIC           292
#define IDB_BROWSEURL_NEW               293
#define IDB_BROWSEURL_NEW_D             294
#define IDB_CHANGECOMBO_CLASSIC         295
#define IDB_CHANGECOMBO_NEW             296
#define IDB_CHANGECOMBO_NEW_D           297
#define IDB_CHANGEFONTMENU_CLASSIC      298
#define IDB_CHANGEFONTMENU_NEW          299
#define IDB_CHANGEFONTMENU_NEW_D        300
#define IDB_CLEARCLIPBOARD_CLASSIC      301
#define IDB_CLEARCLIPBOARD_NEW          302
#define IDB_CLEARCLIPBOARD_NEW_D        303
#define IDB_CLOSE_CLASSIC               304
#define IDB_CLOSE_NEW                   305
#define IDB_CLOSE_NEW_D                 306
#define IDB_COLLAPSEALL_CLASSIC         307
#define IDB_COLLAPSEALL_NEW             308
#define IDB_COLLAPSEALL_NEW_D           309
#define IDB_COMPARE_CLASSIC             310
#define IDB_COMPARE_NEW                 311
#define IDB_COMPARE_NEW_D               312
#define IDB_COPYNOTES_CLASSIC           313
#define IDB_COPYNOTES_NEW               314
#define IDB_COPYNOTES_NEW_D             315
#define IDB_COPYNOTES_NEW32             316
#define IDB_COPYPASSWORD_CLASSIC        317
#define IDB_COPYPASSWORD_NEW            318
#define IDB_COPYPASSWORD_NEW_D          319
#define IDB_COPYUSER_CLASSIC            320
#define IDB_COPYUSER_NEW                321
#define IDB_COPYUSER_NEW_D              322
#define IDB_CREATESHORTCUT_CLASSIC      323
#define IDB_CREATESHORTCUT_NEW          324
#define IDB_CREATESHORTCUT_NEW_D        325
#define IDB_DELETE_CLASSIC              326
#define IDB_DELETE_NEW                  327
#define IDB_DELETE_NEW_D                328
#define IDB_DUPLICATE_CLASSIC           329
#define IDB_DUPLICATE_NEW               330
#define IDB_DUPLICATE_NEW_D             331
#define IDB_EXIT_CLASSIC                332
#define IDB_EXIT_NEW                    333
#define IDB_EXIT_NEW_D                  334
#define IDB_EXPANDALL_CLASSIC           335
#define IDB_EXPANDALL_NEW               336
#define IDB_EXPANDALL_NEW_D             337
#define IDB_EXPORTTEXT_CLASSIC          338
#define IDB_EXPORTTEXT_NEW              339
#define IDB_EXPORTTEXT_NEW_D            340
#define IDB_EXPORTXML_CLASSIC           341
#define IDB_EXPORTXML_NEW               342
#define IDB_EXPORTXML_NEW_D             343
#define IDB_FIND_CLASSIC                344
#define IDB_FIND_NEW                    345
#define IDB_FIND_NEW_D                  346
#define IDB_GROUPENTER_CLASSIC          347
#define IDB_GROUPENTER_NEW              348
#define IDB_GROUPENTER_NEW_D            349
#define IDB_HELP_CLASSIC                350
#define IDB_HELP_NEW                    351
#define IDB_HELP_NEW_D                  352
#define IDB_IMPORTTEXT_CLASSIC          353
#define IDB_IMPORTTEXT_NEW              354
#define IDB_IMPORTTEXT_NEW_D            355
#define IDB_IMPORTXML_CLASSIC           356
#define IDB_IMPORTXML_NEW               357
#define IDB_IMPORTXML_NEW_D             358
#define IDB_LISTTREE_CLASSIC            359
#define IDB_LISTTREE_NEW                360
#define IDB_LISTTREE_NEW_D              361
#define IDB_MERGE_CLASSIC               362
#define IDB_MERGE_NEW                   363
#define IDB_MERGE_NEW_D                 364
#define IDB_NEW_CLASSIC                 365
#define IDB_NEW_NEW                     366
#define IDB_NEW_NEW_D                   367
#define IDB_OPEN_CLASSIC                368
#define IDB_OPEN_NEW                    369
#define IDB_OPEN_NEW_D                  370
#define IDB_OPTIONS_CLASSIC             371
#define IDB_OPTIONS_NEW                 372
#define IDB_OPTIONS_NEW_D               373
#define IDB_PROPERTIES_CLASSIC          374
#define IDB_PROPERTIES_NEW              375
#define IDB_PROPERTIES_NEW_D            376
#define IDB_RESTORE_CLASSIC             377
#define IDB_RESTORE_NEW                 378
#define IDB_RESTORE_NEW_D               379
#define IDB_RESTORE_NEW32               380
#define IDB_SAVE_CLASSIC                381
#define IDB_SAVE_NEW                    382
#define IDB_SAVE_NEW_D                  383
#define IDB_SAVEAS_CLASSIC              384
#define IDB_SAVEAS_NEW                  385
#define IDB_SAVEAS_NEW_D                386
#define IDB_SENDEMAIL_CLASSIC           387
#define IDB_SENDEMAIL_NEW               388
#define IDB_SENDEMAIL_NEW_D             389
#define IDB_TRAYLOCK_CLASSIC            390
#define IDB_TRAYLOCK_NEW                391
#define IDB_TRAYLOCK_NEW_D              392
#define IDB_TRAYUNLOCK_CLASSIC          393
#define IDB_TRAYUNLOCK_NEW              394
#define IDB_TRAYUNLOCK_NEW_D            395
#define IDB_VALIDATE_CLASSIC            396
#define IDB_VALIDATE_NEW                397
#define IDB_VALIDATE_NEW_D              398
#define IDB_VIEWEDIT_CLASSIC            399
#define IDB_VIEWEDIT_NEW                400
#define IDB_VIEWEDIT_NEW_D              401
#define IDB_VIEWREPORTS_CLASSIC         402
#define IDB_VIEWREPORTS_NEW             403
#define IDB_VIEWREPORTS_NEW_D           404
#define IDD_SAMPLETEXT                  405
#define IDB_CHANGEPSWDFONTMENU_CLASSIC  406
#define IDB_CHANGEPSWDFONTMENU_NEW      407
#define IDB_CHANGEPSWDFONTMENU_NEW_D    408
#define IDB_EXPORT_CLASSIC              409
#define IDB_EXPORT_NEW                  410
#define IDB_EXPORT_NEW_D                411
#define IDB_IMPORT_CLASSIC              412
#define IDB_IMPORT_NEW                  413
#define IDB_IMPORT_NEW_D                414
#define IDB_CUSTOMIZETBAR_CLASSIC       415
#define IDB_CUSTOMIZETBAR_NEW           416
#define IDC_APPVERSION                  1000
#define IDC_VERSION                     1001
#define IDC_BROWSE                      1002
#define IDC_CREATE_DB                   1003
#define IDC_EXITADVANCED                1004
#define IDC_PASSWORD                    1005
#define IDC_OLDPASSKEY                  1006
#define IDC_NEWPASSKEY                  1007
#define IDC_CONFIRMNEW                  1008
#define IDC_TITLE                       1009
#define IDC_USERNAME                    1010
#define IDC_NOTES                       1011
#define IDC_ITEMLIST                    1012
#define IDC_ITEMTREE                    1013
#define IDC_SHOWPASSWORD                1014
#define IDC_CLEARCHECK                  1015
#define IDC_PASSKEY                     1016
#define IDC_DELITEM                     1017
#define IDC_VERIFY                      1018
#define IDC_CONFIRMDELETE               1019
#define IDC_CONFIRMCOPY                 1021
#define IDC_TRYAGAIN                    1022
#define IDC_QUIT                        1023
#define IDC_OPEN                        1024
#define IDC_RANDOM                      1025
#define IDC_LOCKBASE                    1026
#define IDC_DEFPWSHOW                   1027
#define IDC_DEFPWSHOWINEDIT             1028
#define IDC_USEDEFUSER                  1029
#define IDC_QUERYSETDEF                 1030
#define IDC_DEFPWSHOWINTREE             1031
#define IDC_CRYPTKEY1                   1032
#define IDC_CRYPTKEY2                   1033
#define IDC_DEFUSERNAME                 1034
#define IDC_STATIC_USERNAME             1035
#define IDC_DEFPWLENGTH                 1036
#define IDC_MESSAGE                     1037
#define IDC_QUERYCHECK                  1038
#define IDC_STATIC_RULES                1039
#define IDC_MAKEDEF                     1040
#define IDC_NEW                         1041
#define IDC_STATIC_LOGO                 1042
#define IDC_ALWAYSONTOP                 1043
#define IDC_STATIC_LOGOTEXT             1044
#define IDC_SAVEIMMEDIATELY             1045
#define IDC_PWLENSPIN                   1046
#define IDC_USELOWERCASE                1047
#define IDC_USEUPPERCASE                1048
#define IDC_USEDIGITS                   1049
#define IDC_USESYMBOLS                  1050
#define IDC_EASYVISION                  1051
#define IDC_PRONOUNCEABLE               1052
#define IDC_MINDIGITLENGTH              1053
#define IDC_MINLOWERLENGTH              1054
#define IDC_MINSYMBOLLENGTH             1055
#define IDC_MINUPPERLENGTH              1056
#define IDC_SPINLOWERCASE               1057
#define IDC_SPINUPPERCASE               1058
#define IDC_SPINDIGITS                  1059
#define IDC_SPINSYMBOLS                 1060
#define IDC_CLEARBOARDONMINIMIZE        1061
#define IDC_CLEARBOARDONEXIT            1062
#define IDC_GROUP                       1067
#define IDC_EXPORT_XML_PASSWORD         1068
#define IDC_EXPORT_TEXT_PASSWORD        1069
#define IDC_USEHEXDIGITS                1070
#define IDC_OVERRIDE_POLICY             1071
#define IDC_DEFPWUSESYSTRAY             1072
#define IDC_LOCKONSCREEN                1073
#define IDC_DEFPWRECENTRYHELP           1074
#define IDC_IDLESPIN                    1075
#define IDC_IDLE_TIMEOUT                1076
#define IDC_LOCK_TIMER                  1077
#define IDC_ESC_EXITS                   1078
#define IDC_TAB                         1079
#define IDC_COMMA                       1080
#define IDC_OTHER                       1081
#define IDC_OTHER_SEPARATOR             1082
#define IDC_NO_GROUP                    1083
#define IDC_YES_GROUP                   1084
#define IDC_GROUP_NAME                  1085
#define IDC_READONLY                    1086
#define IDC_HOTKEY_CTRL                 1087
#define IDC_HOTKEY_ENABLE               1088
#define IDC_DEFIMPDELIM                 1090
#define IDC_QUERYSETEXPDELIM            1091
#define IDC_DEFEXPDELIM                 1092
#define IDC_STATIC_MAXMRUITEMS          1093
#define IDC_MAXMRUITEMS                 1094
#define IDC_STATIC_GBMRU                1095
#define IDC_MRU_ONFILEMENU              1096
#define IDC_STATIC_RESTART              1097
#define IDC_STATIC_MAXREITEMS           1098
#define IDC_MAXREITEMS                  1099
#define IDC_MORE                        1100
#define IDC_URL                         1101
#define IDC_AUTOTYPE                    1102
#define IDC_EXPIRYDATE                  1103
#define IDC_EXPIRYTIME                  1104
#define IDC_STATIC_CURRENT_LTIME        1105
#define IDC_STATIC_URL                  1106
#define IDC_STATIC_AUTO                 1107
#define IDC_STATIC_CTIME                1108
#define IDC_CTIME                       1109
#define IDC_STATIC_PMTIME               1110
#define IDC_PMTIME                      1111
#define IDC_STATIC_ATIME                1112
#define IDC_ATIME                       1113
#define IDC_STATIC_LTIME                1114
#define IDC_LTIME                       1115
#define IDC_STATIC_RMTIME               1116
#define IDC_RMTIME                      1117
#define IDC_LTIME_CLEAR                 1118
#define IDC_LTIME_SET                   1119
#define IDC_LTIME_PICKER                1120
#define IDC_MAINTAINDATETIMESTAMPS      1121
#define IDC_STATIC_DTGROUP              1122
#define IDC_STATIC_DTEXPGROUP           1123
#define IDC_TOP_HIDEABLE                1124
#define IDC_BOTTOM_HIDEABLE             1125
#define IDC_LEFT_HIDEABLE               1126
#define IDC_RIGHT_HIDEABLE              1127
#define IDC_EXPIRED_PASSWORD_LIST       1128
#define IDC_COPY_EXP_TO_CLIPBOARD       1129
#define IDC_RESPIN                      1132
#define IDC_MRUSPIN                     1133
#define IDC_PWHSPIN                     1134
#define IDC_STATIC_PWHGROUP             1135
#define IDC_PWHISTORY_LIST              1136
#define IDC_SAVEPWHISTORY               1137
#define IDC_MAXPWHISTORY                1138
#define IDC_DEFPWHNUM                   1139
#define IDC_COPY_OLDPW_TO_CLIPBOARD     1140
#define IDC_CLEAR_PWHIST                1141
#define IDC_STATIC_PWHIST               1142
#define IDC_SAVE_PWHIST                 1143
#define IDC_STATIC_OLDPW1               1144
#define IDC_SHOW_PWHIST                 1145
#define IDC_XML_IMPORT_RESULTS          1147
#define IDC_PASSWORD2                   1149
#define IDC_CLEAR_HISTORY               1150
#define IDC_ADVANCED_LIST               1152
#define IDC_ADVANCED_SELECTED           1153
#define IDC_ADVANCED_SELECTSOME         1154
#define IDC_ADVANCED_SELECTALL          1155
#define IDC_ADVANCED_DESELECTSOME       1156
#define IDC_ADVANCED_DESELECTALL        1157
#define IDC_ADVANCED_SUBGROUP_SET       1158
#define IDC_ADVANCED_SUBGROUP_NAME      1159
#define IDC_ADVANCED_SUBGROUP_FUNCTION  1160
#define IDC_ADVANCED_SUBGROUP_OBJECT    1161
#define IDC_ADVANCED_SUBGROUP_CASE      1162
#define IDC_PWH_COPY_ALL                1174
#define IDC_PWHIST                      1175
#define IDC_TREE_DISPLAY_COLLAPSED      1176
#define IDC_TREE_DISPLAY_EXPANDED       1177
#define IDC_TREE_DISPLAY_LASTSAVE       1178
#define IDC_PWHSTATUS                   1179
#define IDC_PWHMAX                      1180
#define IDC_DOUBLE_CLICK_ACTION         1181
#define IDC_PWHISTORYNOACTION           1183
#define IDC_RESETPWHISTORYOFF           1184
#define IDC_RESETPWHISTORYON            1185
#define IDC_SETMAXPWHISTORY             1186
#define IDC_APPLYPWHCHANGESNOW          1187
#define IDC_REGDEL_CB                   1188
#define IDC_SHOWNOTES                   1189
#define IDC_DEFNOTESSHOWINEDIT          1190
#define IDC_DATABASENAME                1191
#define IDC_DATABASEFORMAT              1192
#define IDC_NUMGROUPS                   1193
#define IDC_NUMENTRIES                  1194
#define IDC_SAVEDBY                     1195
#define IDC_SAVEDON                     1196
#define IDC_SAVEDAPP                    1197
#define IDC_EDITEXPLANATION             1198
#define IDC_BACKUPBEFORESAVE            1199
#define IDC_DFLTBACKUPPREFIX            1200
#define IDC_USERBACKUPPREFIX            1201
#define IDC_USERBACKUPPREFIXVALUE       1202
#define IDC_BACKUPSUFFIX                1203
#define IDC_DFLTBACKUPLOCATION          1205
#define IDC_USERBACKUPOTHERLOCATION     1207
#define IDC_USERBACKUPOTHRLOCATIONVALUE 1208
#define IDC_BACKUPEXAMPLE               1209
#define IDC_BKPMAXINCSPIN               1210
#define IDC_BACKUPMAXINC                1211
#define IDC_BACKUPMAX                   1212
#define IDC_BROWSEFORLOCATION           1213
#define IDC_REGDEL_BTN                  1216
#define IDC_OTHERBROWSERLOCATION        1217
#define IDC_APPCOPYRIGHT                1218
#define IDC_STARTUP                     1220
#define IDC_REGDEL_GRP                  1221
#define IDC_DATABASECOMBO               1222
#define IDC_BTN_BROWSE                  1223
#define IDC_SPCL_TXT                    1225
#define IDC_EXPWARNING1                 1226
#define IDC_EXPWARNING2                 1227
#define IDC_SELECTBYDATETIME            1228
#define IDC_SELECTBYDAYS                1229
#define IDC_EXPDAYS                     1230
#define IDC_EXPDAYSSPIN                 1231
#define IDC_PREWARNEXPIRY               1232
#define IDC_PREEXPIRYWARNDAYS           1233
#define IDC_PREWARNEXPIRYSPIN           1234
#define IDC_DEFEXPLORERTREE             1235
#define IDC_DEFENABLEGRIDLINES          1246
#define IDC_LIST_HEADER                 1247
#define IDC_CPLIST                      1248
#define IDC_DEFAULTAUTOTYPE             1249
#define IDC_MINIMIZEONAUTOTYPE          1250
#define IDC_ALTBROWSER_CMDLINE          1251
#define IDC_EXPORT_ADVANCED             1252
#define IDC_XML_ADVANCED                1253
#define IDC_DEFUNSHOWINTREE             1254
#define IDC_FILEUUID                    1255
#define IDC_UNKNOWNFIELDS               1256
#define IDC_RESULTLIST                  1257
#define IDC_RESULTLISTHDR               1258
#define IDC_VIEWCOMPAREREPORT           1259
#define IDC_COMPAREORIGINALDB           1260
#define IDC_COMPARECOMPARISONDB         1261
#define IDC_SHOW_IDENTICAL_ENTRIES      1262
#define IDC_STATIC_UNK_FIELDS           1263
#define IDC_DELETECHILDREN              1264
#define IDC_RECORDUNKNOWNFIELDS         1265
#define IDC_STATIC_RECORDUNKNOWNFIELDS  1266
#define IDC_STATICGROUPRUNKNFLDS        1267
#define IDC_VIEWDEPENDENTS              1268
#define IDC_STATIC_ISANALIAS            1269
#define IDC_STATIC_ALIASGRP             1270
#define IDC_NEWVER_STATUS               1272
#define IDC_VISIT_WEBSITE               1273
#define IDC_TRAYICONCOLOUR              1274
#define IDC_TRAYICON                    1275
#define IDC_RST_BLK                     1276
#define IDC_RST_BLUE                    1277
#define IDC_RST_WHITE                   1278
#define IDC_RST_YELLOW                  1279
#define IDC_SETPWPOLICY                 1281
#define IDC_CLEARPWPOLICY               1282
#define IDC_SAMPLETEXT                  1283
#define IDC_TREATWHITESPACEASEMPTY      1284
#define IDC_STATIC_LC1                  1285
#define IDC_STATIC_LC2                  1286
#define IDC_STATIC_UC1                  1287
#define IDC_STATIC_UC2                  1288
#define IDC_STATIC_DG1                  1289
#define IDC_STATIC_DG2                  1290
#define IDC_STATIC_SY1                  1291
#define IDC_STATIC_SY2                  1292
#define IDC_ADDSCEXPLANATION            1293
#define IDC_EDITSCEXPLANATION           1294
#define IDC_STATIC_REMLAST              1295
#define IDC_DEFNTSHOWASTIPSINVIEWS      1296

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        417
#define _APS_NEXT_COMMAND_VALUE         30000
#define _APS_NEXT_CONTROL_VALUE         1297
#define _APS_NEXT_SYMED_VALUE           149
#endif
#endif
