//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PasswordSafe.rc
//
#define IDR_ACCS                        100
#define IDR_MAINFRAME                   101
#define IDR_MAINMENU                    102
#define IDR_POPGROUP                    103
#define IDR_POPMENU                     104
#define IDR_POPTRAY                     105
#define IDR_POPTREE                     106
#define IDB_CLOGO                       107
#define IDB_CLOGO_SMALL                 108
#define IDB_CTEXT                       109
#define IDB_NORMAL                      110
#define IDB_NORMAL_EXPIRED              111
#define IDB_NODE                        112
#define IDB_PSLOGO                      113
#define IDI_TRAY                        117
#define IDI_CORNERICON                  118
#define IDI_LOCKEDICON                  119
#define IDI_UNLOCKEDICON                120
#define IDI_MBASKICON                   121
#define IDI_MBINFOICON                  122
#define IDI_MBSTOPICON                  123
#define IDI_MBWARNICON                  124
#define IDB_NORMAL_WARNEXPIRED          125
#define IDR_POPCOLUMNS                  126
#define IDR_POPCOPYTOCOMPARISON         127
#define IDR_POPCOPYTOORIGINAL           128
#define IDI_TRAY_BLUE                   129
#define IDI_TRAY_WHITE                  130
#define IDI_TRAY_YELLOW                 131
#define IDB_ALIAS                       132
#define IDB_ABASE                       133
#define IDB_ABASE_EXPIRED               134
#define IDB_ABASE_WARNEXPIRED           135
#define IDI_NORMAL                      140
#define IDI_NORMAL_EXPIRED              141
#define IDI_NORMAL_WARNEXPIRED          142
#define IDI_ALIAS                       143
#define IDI_ABASE                       144
#define IDI_ABASE_EXPIRED               145
#define IDI_ABASE_WARNEXPIRED           146
#define IDD_ABOUTBOX                    200
#define IDD_PASSWORDSAFE_DIALOG         202
#define IDD_KEYCHANGE_DIALOG            203
#define IDD_PASSKEYSETUP                204
#define IDD_SECURECLEAR                 205
#define IDD_PASSKEYENTRY_FIRST          206
#define IDD_CONFIRMDELETE_DIALOG        207
#define IDD_OPTIONS                     208
#define IDD_EDIT                        209
#define IDD_MINIMIZECLEAR_DIALOG        210
#define IDD_ADD                         211
#define IDD_TRYAGAIN                    212
#define IDD_CRYPTKEYENTRY               213
#define IDD_QUERYSETDEF                 214
#define IDD_USERNAMEENTRY               215
#define IDD_PASSKEYENTRY                216
#define IDD_PASSKEYENTRY_WITHEXIT       217
#define IDD_PS_SECURITY                 218
#define IDD_PS_DISPLAY                  219
#define IDD_PS_PASSWORDHISTORY          220
#define IDD_PS_PASSWORDPOLICY           221
#define IDD_PS_MISC                     222
#define IDD_EXPORT_TEXT                 223
#define IDD_EXPORT_XML                  224
#define IDD_PS_BACKUP                   225
#define IDD_IMPORT_TEXT                 226
#define IDD_PICKEXPDATETIME             227
#define IDD_DISPLAY_EXPIRED_ENTRIES     228
#define IDD_IMPORT_XML                  229
#define IDD_ADVANCED                    231
#define IDD_DLG_PWHIST                  232
#define IDD_PS_SYSTEM                   233
#define IDD_PROPERTIES                  234
#define IDD_COLUMNCHOOSER               236
#define IDD_ADVANCEDMERGE               237
#define IDD_COMPARE_RESULTS             238
#define IDR_POPCUSTOMIZETOOLBAR         239
#define IDB_ADD_CLASSIC                 240
#define IDB_ADD_NEW32                   241
#define IDB_ADD_NEW8                    242
#define IDB_AUTOTYPE_CLASSIC            243
#define IDB_AUTOTYPE_NEW32              244
#define IDB_AUTOTYPE_NEW8               245
#define IDB_BROWSEURL_CLASSIC           246
#define IDB_BROWSEURL_NEW32             247
#define IDB_BROWSEURL_NEW8              248
#define IDB_CLEARCLIPBOARD_CLASSIC      249
#define IDB_CLEARCLIPBOARD_NEW32        250
#define IDB_CLEARCLIPBOARD_NEW8         251
#define IDB_CLOSE_CLASSIC               252
#define IDB_CLOSE_NEW32                 253
#define IDB_CLOSE_NEW8                  254
#define IDB_COLLAPSEALL_CLASSIC         255
#define IDB_COLLAPSEALL_NEW32           256
#define IDB_COLLAPSEALL_NEW8            257
#define IDB_COPYNOTES_CLASSIC           258
#define IDB_COPYNOTES_NEW32             259
#define IDB_COPYNOTES_NEW8              260
#define IDB_COPYPASSWORD_CLASSIC        261
#define IDB_COPYPASSWORD_NEW32          262
#define IDB_COPYPASSWORD_NEW8           263
#define IDB_COPYUSER_CLASSIC            264
#define IDB_COPYUSER_NEW32              265
#define IDB_COPYUSER_NEW8               266
#define IDB_DELETE_CLASSIC              267
#define IDB_DELETE_NEW32                268
#define IDB_DELETE_NEW8                 269
#define IDB_EXPANDALL_CLASSIC           270
#define IDB_EXPANDALL_NEW32             271
#define IDB_EXPANDALL_NEW8              272
#define IDB_HELP_CLASSIC                273
#define IDB_HELP_NEW32                  274
#define IDB_HELP_NEW8                   275
#define IDB_NEW_CLASSIC                 276
#define IDB_NEW_NEW32                   277
#define IDB_NEW_NEW8                    278
#define IDB_OPEN_CLASSIC                279
#define IDB_OPEN_NEW32                  280
#define IDB_OPEN_NEW8                   281
#define IDB_SAVE_CLASSIC                282
#define IDB_SAVE_NEW32                  283
#define IDB_SAVE_NEW8                   284
#define IDB_VIEWEDIT_CLASSIC            285
#define IDB_VIEWEDIT_NEW32              286
#define IDB_VIEWEDIT_NEW8               287
#define IDB_FINDADVANCED_CLASSIC        288
#define IDB_FINDADVANCED_NEW32          289
#define IDB_FINDADVANCED_NEW8           290
#define IDB_FINDCASE_I_CLASSIC          291
#define IDB_FINDCASE_I_NEW32            292
#define IDB_FINDCASE_I_NEW8             293
#define IDB_FINDCASE_S_CLASSIC          294
#define IDB_FINDCASE_S_NEW32            295
#define IDB_FINDCASE_S_NEW8             296
#define IDB_FINDCLEAR_CLASSIC           297
#define IDB_FINDCLEAR_NEW32             298
#define IDB_FINDCLEAR_NEW8              299
#define IDB_FINDCLOSE_CLASSIC           300
#define IDB_FINDCLOSE_NEW32             301
#define IDB_FINDCLOSE_NEW8              302
#define IDB_FINDCTRLPLACEHOLDER         303
#define IDB_FIND_CLASSIC                304
#define IDB_FIND_NEW32                  305
#define IDB_FIND_NEW8                   306
#define IDB_SENDEMAIL_CLASSIC           307
#define IDB_SENDEMAIL_NEW8              308
#define IDB_SENDEMAIL_NEW32             309
#define IDB_OPTIONS_CLASSIC             310
#define IDB_OPTIONS_NEW8                311
#define IDB_OPTIONS_NEW32               312
#define IDB_EXPORTTEXT_CLASSIC          313
#define IDB_EXPORTTEXT_NEW8             314
#define IDB_EXPORTTEXT_NEW32            315
#define IDB_EXPORTXML_CLASSIC           316
#define IDB_EXPORTXML_NEW8              317
#define IDB_EXPORTXML_NEW32             318
#define IDB_IMPORTTEXT_CLASSIC          319
#define IDB_IMPORTTEXT_NEW8             320
#define IDB_IMPORTTEXT_NEW32            321
#define IDB_IMPORTXML_CLASSIC           322
#define IDB_IMPORTXML_NEW8              323
#define IDB_IMPORTXML_NEW32             324
#define IDB_SAVEAS_CLASSIC              325
#define IDB_SAVEAS_NEW8                 326
#define IDB_SAVEAS_NEW32                327
#define IDB_COMPARE_CLASSIC             328
#define IDB_COMPARE_NEW8                329
#define IDB_COMPARE_NEW32               330
#define IDB_MERGE_CLASSIC               331
#define IDB_MERGE_NEW8                  332
#define IDB_MERGE_NEW32                 333
#define IDB_LISTTREE_CLASSIC            334
#define IDB_LISTTREE_NEW8               335
#define IDB_LISTTREE_NEW32              336
#define IDB_VIEWREPORTS_CLASSIC         337
#define IDB_VIEWREPORTS_NEW8            338
#define IDB_VIEWREPORTS_NEW32           339
#define IDC_APPVERSION                  1000
#define IDC_VERSION                     1001
#define IDC_BROWSE                      1002
#define IDC_CREATE_DB                   1003
#define IDC_EXITADVANCED                1004
#define IDC_PASSWORD                    1005
#define IDC_OLDPASSKEY                  1006
#define IDC_NEWPASSKEY                  1007
#define IDC_CONFIRMNEW                  1008
#define IDC_TITLE                       1009
#define IDC_USERNAME                    1010
#define IDC_NOTES                       1011
#define IDC_ITEMLIST                    1012
#define IDC_SHOWPASSWORD                1013
#define IDC_CLEARCHECK                  1014
#define IDC_PASSKEY                     1015
#define IDC_DELITEM                     1016
#define IDC_VERIFY                      1017
#define IDC_CONFIRMDELETE               1018
#define IDC_CLEARBOARD                  1019
#define IDC_CONFIRMCOPY                 1020
#define IDC_TRYAGAIN                    1021
#define IDC_QUIT                        1022
#define IDC_OPEN                        1023
#define IDC_RANDOM                      1024
#define IDC_LOCKBASE                    1025
#define IDC_DEFPWSHOW                   1026
#define IDC_DEFPWSHOWINEDIT             1027
#define IDC_USEDEFUSER                  1028
#define IDC_QUERYSETDEF                 1029
#define IDC_DEFPWSHOWINLIST             1030
#define IDC_CRYPTKEY1                   1031
#define IDC_CRYPTKEY2                   1032
#define IDC_DEFUSERNAME                 1033
#define IDC_STATIC_USERNAME             1034
#define IDC_DEFPWLENGTH                 1035
#define IDC_MESSAGE                     1036
#define IDC_STATIC_DEFPWLENGTH          1037
#define IDC_QUERYCHECK                  1038
#define IDC_STATIC_RULES                1039
#define IDC_STATIC_MINLOWERCASE         1040
#define IDC_MAKEDEF                     1041
#define IDC_STATIC_MINUPPERCASE         1042
#define IDC_NEW                         1043
#define IDC_STATIC_MINDIGITS            1044
#define IDC_STATIC_MINSYMBOLS           1045
#define IDC_MINLOWERCASE                1046
#define IDC_MINUPPERCASE                1047
#define IDC_STATIC_LOGO                 1048
#define IDC_MINSYMBOLS                  1049
#define IDC_ALWAYSONTOP                 1053
#define IDC_STATIC_LOGOTEXT             1054
#define IDC_SAVEIMMEDIATELY             1055
#define IDC_PWLENSPIN                   1056
#define IDC_USELOWERCASE                1057
#define IDC_USEUPPERCASE                1058
#define IDC_USEDIGITS                   1059
#define IDC_USESYMBOLS                  1060
#define IDC_SPINLOWERCASE               1061
#define IDC_SPINUPPERCASE               1062
#define IDC_SPINDIGITS                  1063
#define IDC_SPINSYMBOLS                 1064
#define IDC_EASYVISION                  1065
#define IDC_ITEMTREE                    1066
#define IDC_GROUP                       1067
#define IDC_EXPORT_XML_PASSWORD         1068
#define IDC_EXPORT_TEXT_PASSWORD        1069
#define IDC_USEHEXDIGITS                1070
#define IDC_OVERRIDE_POLICY             1071
#define IDC_DEFPWUSESYSTRAY             1072
#define IDC_LOCKONSCREEN                1073
#define IDC_DEFPWRECENTRYHELP           1074
#define IDC_IDLESPIN                    1075
#define IDC_IDLE_TIMEOUT                1076
#define IDC_LOCK_TIMER                  1077
#define IDC_ESC_EXITS                   1078
#define IDC_TAB                         1079
#define IDC_COMMA                       1080
#define IDC_OTHER                       1081
#define IDC_OTHER_SEPARATOR             1082
#define IDC_NO_GROUP                    1083
#define IDC_YES_GROUP                   1084
#define IDC_GROUP_NAME                  1085
#define IDC_READONLY                    1086
#define IDC_HOTKEY_CTRL                 1087
#define IDC_HOTKEY_ENABLE               1088
#define IDC_DEFIMPDELIM                 1090
#define IDC_QUERYSETEXPDELIM            1091
#define IDC_DEFEXPDELIM                 1092
#define IDC_STATIC_MAXMRUITEMS          1093
#define IDC_MAXMRUITEMS                 1094
#define IDC_STATIC_GBMRU                1095
#define IDC_MRU_ONFILEMENU              1096
#define IDC_STATIC_RESTART              1097
#define IDC_STATIC_MAXREITEMS           1098
#define IDC_MAXREITEMS                  1099
#define IDC_MORE                        1100
#define IDC_URL                         1101
#define IDC_AUTOTYPE                    1102
#define IDC_EXPIRYDATE                  1103
#define IDC_EXPIRYTIME                  1104
#define IDC_STATIC_CURRENT_LTIME        1105
#define IDC_STATIC_URL                  1106
#define IDC_STATIC_AUTO                 1107
#define IDC_STATIC_CTIME                1108
#define IDC_CTIME                       1109
#define IDC_STATIC_PMTIME               1110
#define IDC_PMTIME                      1111
#define IDC_STATIC_ATIME                1112
#define IDC_ATIME                       1113
#define IDC_STATIC_LTIME                1114
#define IDC_LTIME                       1115
#define IDC_STATIC_RMTIME               1116
#define IDC_RMTIME                      1117
#define IDC_LTIME_CLEAR                 1118
#define IDC_LTIME_SET                   1119
#define IDC_LTIME_PICKER                1120
#define IDC_MAINTAINDATETIMESTAMPS      1121
#define IDC_STATIC_DTGROUP              1122
#define IDC_STATIC_DTEXPGROUP           1123
#define IDC_TOP_HIDEABLE                1124
#define IDC_BOTTOM_HIDEABLE             1125
#define IDC_LEFT_HIDEABLE               1126
#define IDC_RIGHT_HIDEABLE              1127
#define IDC_EXPIRED_PASSWORD_LIST       1128
#define IDC_COPY_EXP_TO_CLIPBOARD       1129
#define IDC_RESPIN                      1132
#define IDC_MRUSPIN                     1133
#define IDC_PWHSPIN                     1134
#define IDC_STATIC_PWHGROUP             1135
#define IDC_PWHISTORY_LIST              1136
#define IDC_SAVEPWHISTORY               1137
#define IDC_MAXPWHISTORY                1138
#define IDC_DEFPWHNUM                   1139
#define IDC_COPY_OLDPW_TO_CLIPBOARD     1140
#define IDC_CLEAR_PWHIST                1141
#define IDC_STATIC_PWHIST               1142
#define IDC_SAVE_PWHIST                 1143
#define IDC_STATIC_OLDPW1               1144
#define IDC_SHOW_PWHIST                 1145
#define IDC_XML_IMPORT_RESULTS          1147
#define IDC_PASSWORD2                   1149
#define IDC_CLEAR_HISTORY               1150
#define IDC_ADVANCED_LIST               1152
#define IDC_ADVANCED_SELECTED           1153
#define IDC_ADVANCED_SELECTSOME         1154
#define IDC_ADVANCED_SELECTALL          1155
#define IDC_ADVANCED_DESELECTSOME       1156
#define IDC_ADVANCED_DESELECTALL        1157
#define IDC_ADVANCED_SUBGROUP_SET       1158
#define IDC_ADVANCED_SUBGROUP_NAME      1159
#define IDC_ADVANCED_SUBGROUP_FUNCTION  1160
#define IDC_ADVANCED_SUBGROUP_OBJECT    1161
#define IDC_ADVANCED_SUBGROUP_CASE      1162
#define IDC_PWH_COPY_ALL                1174
#define IDC_PWHIST                      1175
#define IDC_TREE_DISPLAY_COLLAPSED      1176
#define IDC_TREE_DISPLAY_EXPANDED       1177
#define IDC_TREE_DISPLAY_LASTSAVE       1178
#define IDC_PWHSTATUS                   1179
#define IDC_PWHMAX                      1180
#define IDC_DOUBLE_CLICK_ACTION         1181
#define IDC_PWHISTORYNOACTION           1183
#define IDC_RESETPWHISTORYOFF           1184
#define IDC_RESETPWHISTORYON            1185
#define IDC_SETMAXPWHISTORY             1186
#define IDC_APPLYPWHCHANGESNOW          1187
#define IDC_REGDEL_CB                   1188
#define IDC_SHOWNOTES                   1189
#define IDC_DEFNOTESSHOWINEDIT          1190
#define IDC_DATABASENAME                1191
#define IDC_DATABASEFORMAT              1192
#define IDC_NUMGROUPS                   1193
#define IDC_NUMENTRIES                  1194
#define IDC_SAVEDBY                     1195
#define IDC_SAVEDON                     1196
#define IDC_SAVEDAPP                    1197
#define IDC_EDITEXPLANATION             1198
#define IDC_BACKUPBEFORESAVE            1199
#define IDC_DFLTBACKUPPREFIX            1200
#define IDC_USERBACKUPPREFIX            1201
#define IDC_USERBACKUPPREFIXVALUE       1202
#define IDC_BACKUPSUFFIX                1203
#define IDC_DFLTBACKUPLOCATION          1205
#define IDC_USERBACKUPOTHERLOCATION     1207
#define IDC_USERBACKUPOTHRLOCATIONVALUE 1208
#define IDC_BACKUPEXAMPLE               1209
#define IDC_BKPMAXINCSPIN               1210
#define IDC_BACKUPMAXINC                1211
#define IDC_BACKUPMAX                   1212
#define IDC_BROWSEFORLOCATION           1213
#define IDC_REGDEL_BTN                  1216
#define IDC_OTHERBROWSERLOCATION        1217
#define IDC_APPCOPYRIGHT                1218
#define IDC_STARTUP                     1220
#define IDC_REGDEL_GRP                  1221
#define IDC_DATABASECOMBO               1222
#define IDC_BTN_BROWSE                  1223
#define IDC_SPCL_TXT                    1225
#define IDC_EXPWARNING1                 1226
#define IDC_EXPWARNING2                 1227
#define IDC_SELECTBYDATETIME            1228
#define IDC_SELECTBYDAYS                1229
#define IDC_EXPDAYS                     1230
#define IDC_EXPDAYSSPIN                 1231
#define IDC_PREWARNEXPIRY               1232
#define IDC_PREEXPIRYWARNDAYS           1233
#define IDC_PREWARNEXPIRYSPIN           1234
#define IDC_DEFEXPLORERTREE             1235
#define IDC_DEFENABLEGRIDLINES          1246
#define IDC_LIST_HEADER                 1247
#define IDC_CPLIST                      1248
#define IDC_DEFAULTAUTOTYPE             1249
#define IDC_MINIMIZEONAUTOTYPE          1250
#define IDC_ALTBROWSER_CMDLINE          1251
#define IDC_EXPORT_ADVANCED             1252
#define IDC_XML_ADVANCED                1253
#define IDC_DEFUNSHOWINTREE             1254
#define IDC_FILEUUID                    1255
#define IDC_UNKNOWNFIELDS               1256
#define IDC_RESULTLIST                  1257
#define IDC_RESULTLISTHDR               1258
#define IDC_VIEWCOMPAREREPORT           1259
#define IDC_COMPAREORIGINALDB           1260
#define IDC_COMPARECOMPARISONDB         1261
#define IDC_SHOW_IDENTICAL_ENTRIES      1262
#define IDC_STATIC_UNK_FIELDS           1263
#define IDC_DELETECHILDREN              1264
#define IDC_RECORDUNKNOWNFIELDS         1265
#define IDC_STATIC_RECORDUNKNOWNFIELDS  1266
#define IDC_STATICGROUPRUNKNFLDS        1267
#define IDC_VIEWALIASES                 1268
#define IDC_STATIC_ISANALIAS            1269
#define IDC_STATIC_ALIASGRP             1270
#define IDC_NEWVER_STATUS               1272
#define IDC_VISIT_WEBSITE               1273
#define IDC_TRAYICONCOLOUR              1274
#define IDC_TRAYICON                    1275
#define IDC_RST_BLK                     1276
#define IDC_RST_BLUE                    1277
#define IDC_RST_WHITE                   1278
#define IDC_RST_YELLOW                  1279

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         30000
#define _APS_NEXT_CONTROL_VALUE         1280
#define _APS_NEXT_SYMED_VALUE           151
#endif
#endif
