image: ubuntu/next
arch: amd64
triggers:
    - action: email
      condition: failure
      to: build@pwsafe.org
sources: 
    - https://git.sr.ht/~ronys/pwsafe
tasks:
    - setup: |
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update
        sudo pwsafe/Misc/setup-linux-dev-env.sh
        cd pwsafe
        mkdir build build-dbg
        cd build
        cmake .. -D CMAKE_BUILD_TYPE=Release
        cd ../build-dbg
        cmake .. -D CMAKE_BUILD_TYPE=Debug

    - build-dbg: |
        cd pwsafe/build-dbg
        make
    - test: |
        cd pwsafe/build-dbg
        LC_ALL=C.UTF-8 make test
