#!/bin/bash
xdg-icon-resource install --novendor --size 48 --mode system \
                  /usr/share/pwsafe/pwsafe.png
xdg-desktop-menu install --novendor --mode system \
                  /usr/share/pwsafe/pwsafe.desktop
exit 0
