BASEDIRNAME=pwsafe
LANGS=RU DE ES FR ZH PL

ZIP = /usr/bin/zip

all: default $(LANGS)

default:
	@cd default ; $(ZIP) -qr help ./* -x \*/.svn/\*

$(LANGS):
	@cd $(BASEDIRNAME)$@ ; $(ZIP) -qr ../help$@ ./* -x \*/.svn/\*

clean:
	$(RM) *.zip

.PHONY: all clean default $(LANGS)

# Local variables:
# mode: makefile
# End:
