# Toplevel Makefile for Linux build of PasswordSafe

all clean unicodedebug unicoderelease:
	$(MAKE) -C src/os/linux $@
	$(MAKE) -C src/corelib $@
	$(MAKE) -C src/ui/wxWidgets $@

debug:
	$(MAKE) unicodedebug

release:
	$(MAKE) unicoderelease

reallyclean:
	$(MAKE) clean CONFIG=unicodebug
	$(MAKE) clean CONFIG=unicorelease

.PHONY:	all clean reallyclean debug release unicodedebug unicoderelease
# Local variables:
# mode: makefile
# End:
