//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PasswordSafe.rc
//
#define IDR_ACCS                        100
#define IDR_MAINFRAME                   101
#define IDR_MAINMENU                    102
#define IDR_POPGROUP                    103
#define IDR_POPMENU                     104
#define IDR_POPTRAY                     105
#define IDR_POPTREE                     106
#define IDB_CLOGO                       107
#define IDB_CLOGO_SMALL                 108
#define IDB_CTEXT                       109
#define IDB_LEAF                        110
#define IDB_LEAF_EXPIRED                111
#define IDB_NODE                        112
#define IDB_PSLOGO                      113
#define IDB_TOOLBAR1                    114
#define IDB_TOOLBAR2                    115
#define IDB_TOOLBAR3                    116
#define IDI_TRAY                        117
#define IDI_CORNERICON                  118
#define IDI_LOCKEDICON                  119
#define IDI_UNLOCKEDICON                120
#define IDI_MBASKICON                   121
#define IDI_MBINFOICON                  122
#define IDI_MBSTOPICON                  123
#define IDI_MBWARNICON                  124
#define IDB_LEAF_WARNEXPIRED            125
#define IDR_POPCOLUMNS                  126
#define IDD_ABOUTBOX                    200
#define IDD_FIND                        201
#define IDD_PASSWORDSAFE_DIALOG         202
#define IDD_KEYCHANGE_DIALOG            203
#define IDD_PASSKEYSETUP                204
#define IDD_SECURECLEAR                 205
#define IDD_PASSKEYENTRY_FIRST          206
#define IDD_CONFIRMDELETE_DIALOG        207
#define IDD_OPTIONS                     208
#define IDD_EDIT                        209
#define IDD_MINIMIZECLEAR_DIALOG        210
#define IDD_ADD                         211
#define IDD_TRYAGAIN                    212
#define IDD_CRYPTKEYENTRY               213
#define IDD_QUERYSETDEF                 214
#define IDD_USERNAMEENTRY               215
#define IDD_PASSKEYENTRY                216
#define IDD_PASSKEYENTRY_WITHEXIT       217
#define IDD_PS_SECURITY                 218
#define IDD_PS_DISPLAY                  219
#define IDD_PS_PASSWORDHISTORY          220
#define IDD_PS_PASSWORDPOLICY           221
#define IDD_PS_MISC                     222
#define IDD_EXPORT_TEXT                 223
#define IDD_EXPORT_XML                  224
#define IDD_PS_BACKUP                   225
#define IDD_IMPORT_TEXT                 226
#define IDD_PICKEXPDATETIME             227
#define IDD_DISPLAY_EXPIRED_ENTRIES     228
#define IDD_IMPORT_XML                  229
#define IDD_IMPORT_XML_ERRORS           230
#define IDD_EXPORT_TEXTX                231
#define IDD_DLG_PWHIST                  232
#define IDD_PS_SYSTEM                   233
#define IDD_PROPERTIES                  234
#define IDD_COLUMNPICKER                235
#define IDC_APPVERSION                  1000
#define IDC_VERSION                     1001
#define IDC_BROWSE                      1002
#define IDC_CREATE_DB                   1003
#define IDC_EXIT                        1004
#define IDC_PASSWORD                    1005
#define IDC_OLDPASSKEY                  1006
#define IDC_NEWPASSKEY                  1007
#define IDC_CONFIRMNEW                  1008
#define IDC_TITLE                       1009
#define IDC_USERNAME                    1010
#define IDC_NOTES                       1011
#define IDC_ITEMLIST                    1012
#define IDC_SHOWPASSWORD                1013
#define IDC_CLEARCHECK                  1014
#define IDC_PASSKEY                     1015
#define IDC_DELITEM                     1016
#define IDC_VERIFY                      1017
#define IDC_CONFIRMDELETE               1018
#define IDC_CLEARBOARD                  1019
#define IDC_CONFIRMCOPY                 1020
#define IDC_TRYAGAIN                    1021
#define IDC_QUIT                        1022
#define IDC_OPEN                        1023
#define IDC_RANDOM                      1024
#define IDC_LOCKBASE                    1025
#define IDC_DEFPWSHOW                   1026
#define IDC_DEFPWSHOWINEDIT             1027
#define IDC_USEDEFUSER                  1028
#define IDC_QUERYSETDEF                 1029
#define IDC_DEFPWSHOWINLIST             1030
#define IDC_CRYPTKEY1                   1031
#define IDC_CRYPTKEY2                   1032
#define IDC_DEFUSERNAME                 1033
#define IDC_STATIC_USERNAME             1034
#define IDC_DEFPWLENGTH                 1035
#define IDC_MESSAGE                     1036
#define IDC_STATIC_DEFPWLENGTH          1037
#define IDC_QUERYCHECK                  1038
#define IDC_STATIC_RULES                1039
#define IDC_STATIC_MINLOWERCASE         1040
#define IDC_MAKEDEF                     1041
#define IDC_STATIC_MINUPPERCASE         1042
#define IDC_NEW                         1043
#define IDC_STATIC_MINDIGITS            1044
#define IDC_STATIC_MINSYMBOLS           1045
#define IDC_MINLOWERCASE                1046
#define IDC_MINUPPERCASE                1047
#define IDC_STATIC_LOGO                 1048
#define IDC_MINSYMBOLS                  1049
#define IDC_FIND_TEXT                   1050
#define IDC_FIND_CS                     1051
#define IDC_STATUS                      1052
#define IDC_ALWAYSONTOP                 1053
#define IDC_STATIC_LOGOTEXT             1054
#define IDC_SAVEIMMEDIATELY             1055
#define IDC_PWLENSPIN                   1056
#define IDC_USELOWERCASE                1057
#define IDC_USEUPPERCASE                1058
#define IDC_USEDIGITS                   1059
#define IDC_USESYMBOLS                  1060
#define IDC_SPINLOWERCASE               1061
#define IDC_SPINUPPERCASE               1062
#define IDC_SPINDIGITS                  1063
#define IDC_SPINSYMBOLS                 1064
#define IDC_EASYVISION                  1065
#define IDC_ITEMTREE                    1066
#define IDC_GROUP                       1067
#define IDC_EXPORT_XML_PASSWORD         1068
#define IDC_EXPORT_TEXT_PASSWORD        1069
#define IDC_USEHEXDIGITS                1070
#define IDC_OVERRIDE_POLICY             1071
#define IDC_DEFPWUSESYSTRAY             1072
#define IDC_LOCKONSCREEN                1073
#define IDC_DEFPWRECENTRYHELP           1074
#define IDC_IDLESPIN                    1075
#define IDC_IDLE_TIMEOUT                1076
#define IDC_LOCK_TIMER                  1077
#define IDC_ESC_EXITS                   1078
#define IDC_TAB                         1079
#define IDC_COMMA                       1080
#define IDC_OTHER                       1081
#define IDC_OTHER_SEPARATOR             1082
#define IDC_NO_GROUP                    1083
#define IDC_YES_GROUP                   1084
#define IDC_GROUP_NAME                  1085
#define IDC_READONLY                    1086
#define IDC_HOTKEY_CTRL                 1087
#define IDC_HOTKEY_ENABLE               1088
#define IDC_DEFIMPDELIM                 1090
#define IDC_QUERYSETEXPDELIM            1091
#define IDC_DEFEXPDELIM                 1092
#define IDC_STATIC_MAXMRUITEMS          1093
#define IDC_MAXMRUITEMS                 1094
#define IDC_STATIC_GBMRU                1095
#define IDC_MRU_ONFILEMENU              1096
#define IDC_STATIC_RESTART              1097
#define IDC_STATIC_MAXREITEMS           1098
#define IDC_MAXREITEMS                  1099
#define IDC_MORE                        1100
#define IDC_URL                         1101
#define IDC_AUTOTYPE                    1102
#define IDC_EXPIRYDATE                  1103
#define IDC_EXPIRYTIME                  1104
#define IDC_STATIC_CURRENT_LTIME        1105
#define IDC_STATIC_URL                  1106
#define IDC_STATIC_AUTO                 1107
#define IDC_STATIC_CTIME                1108
#define IDC_CTIME                       1109
#define IDC_STATIC_PMTIME               1110
#define IDC_PMTIME                      1111
#define IDC_STATIC_ATIME                1112
#define IDC_ATIME                       1113
#define IDC_STATIC_LTIME                1114
#define IDC_LTIME                       1115
#define IDC_STATIC_RMTIME               1116
#define IDC_RMTIME                      1117
#define IDC_LTIME_CLEAR                 1118
#define IDC_LTIME_SET                   1119
#define IDC_LTIME_PICKER                1120
#define IDC_MAINTAINDATETIMESTAMPS      1121
#define IDC_STATIC_DTGROUP              1122
#define IDC_STATIC_DTEXPGROUP           1123
#define IDC_TOP_HIDEABLE                1124
#define IDC_BOTTOM_HIDEABLE             1125
#define IDC_LEFT_HIDEABLE               1126
#define IDC_RIGHT_HIDEABLE              1127
#define IDC_EXPIRED_PASSWORD_LIST       1128
#define IDC_COPY_EXP_TO_CLIPBOARD       1129
#define IDC_RESPIN                      1132
#define IDC_MRUSPIN                     1133
#define IDC_PWHSPIN                     1134
#define IDC_STATIC_PWHGROUP             1135
#define IDC_PWHISTORY_LIST              1136
#define IDC_SAVEPWHISTORY               1137
#define IDC_MAXPWHISTORY                1138
#define IDC_DEFPWHNUM                   1139
#define IDC_COPY_OLDPW_TO_CLIPBOARD     1140
#define IDC_CLEAR_PWHIST                1141
#define IDC_STATIC_PWHIST               1142
#define IDC_SAVE_PWHIST                 1143
#define IDC_STATIC_OLDPW1               1144
#define IDC_SHOW_PWHIST                 1145
#define IDC_XML_IMPORT_ACTION           1146
#define IDC_XML_IMPORT_RESULTS          1147
#define IDC_COPY_ERRORS_TO_CLIPBOARD    1148
#define IDC_PASSWORD2                   1149
#define IDC_CLEAR_HISTORY               1150
#define IDC_EXPORT_ADVANCED             1151
#define IDC_EXPORTX_GROUP_TITLE         1152
#define IDC_EXPORTX_USER                1153
#define IDC_EXPORTX_NOTES               1154
#define IDC_EXPORTX_PASSWORD            1155
#define IDC_EXPORTX_CTIME               1156
#define IDC_EXPORTX_PMTIME              1157
#define IDC_EXPORTX_ATIME               1158
#define IDC_EXPORTX_LTIME               1159
#define IDC_EXPORTX_RMTIME              1160
#define IDC_EXPORTX_URL                 1161
#define IDC_EXPORTX_AUTOTYPE            1162
#define IDC_EXPORTX_PWHIST              1163
#define IDC_EXPORTX_SETTIMES            1164
#define IDC_EXPORTX_CLEARTIMES          1165
#define IDC_EXPORTX_SUBGROUP            1166
#define IDC_EXPORTX_SUBGROUP_NAME       1167
#define IDC_EXPORTX_SETALL              1168
#define IDC_EXPORTX_CLEARALL            1169
#define IDC_EXPORTX_SUBGROUP_FUNCTION   1170
#define IDC_EXPORTX_SUBGROUP_OBJECT     1171
#define IDC_EXPORTX_SUBGROUP_CASE       1172
#define IDC_PWH_COPY_ALL                1173
#define IDC_PWHIST                      1174
#define IDC_TREE_DISPLAY_COLLAPSED      1175
#define IDC_TREE_DISPLAY_EXPANDED       1176
#define IDC_TREE_DISPLAY_LASTSAVE       1177
#define IDC_PWHSTATUS                   1178
#define IDC_PWHMAX                      1179
#define IDC_DOUBLE_CLICK_ACTION         1180
#define IDC_FIND_WRAP                   1181
#define IDC_PWHISTORYNOACTION           1182
#define IDC_RESETPWHISTORYOFF           1183
#define IDC_RESETPWHISTORYON            1184
#define IDC_SETMAXPWHISTORY             1185
#define IDC_APPLYPWHCHANGESNOW          1186
#define IDC_REGDEL_CB                   1187
#define IDC_SHOWNOTES                   1188
#define IDC_DEFNOTESSHOWINEDIT          1189
#define IDC_DATABASENAME                1190
#define IDC_DATABASEFORMAT              1191
#define IDC_NUMGROUPS                   1192
#define IDC_NUMENTRIES                  1193
#define IDC_SAVEDBY                     1194
#define IDC_SAVEDON                     1195
#define IDC_SAVEDAPP                    1196
#define IDC_EDITEXPLANATION             1197
#define IDC_BACKUPBEFORESAVE            1198
#define IDC_DFLTBACKUPPREFIX            1199
#define IDC_USERBACKUPPREFIX            1200
#define IDC_USERBACKUPPREFIXVALUE       1201
#define IDC_BACKUPSUFFIX                1202
#define IDC_DFLTBACKUPLOCATION          1203
#define IDC_USERBACKUPOTHERLOCATION     1205
#define IDC_USERBACKUPOTHRLOCATIONVALUE 1207
#define IDC_BACKUPEXAMPLE               1208
#define IDC_BKPMAXINCSPIN               1209
#define IDC_BACKUPMAXINC                1210
#define IDC_BACKUPMAX                   1211
#define IDC_BROWSEFORLOCATION           1212
#define IDC_REGDEL_BTN                  1213
#define IDC_OTHERBROWSERLOCATION        1216
#define IDC_APPCOPYRIGHT                1217
#define IDC_STARTUP                     1218
#define IDC_REGDEL_GRP                  1220
#define IDC_COMBO1                      1221
#define IDC_BTN_BROWSE                  1222
#define IDC_SPCL_TXT                    1223
#define IDC_EXPWARNING1                 1225
#define IDC_EXPWARNING2                 1226
#define IDC_SELECTBYDATETIME            1227
#define IDC_SELECTBYDAYS                1228
#define IDC_EXPDAYS                     1229
#define IDC_EXPDAYSSPIN                 1230
#define IDC_PREWARNEXPIRY               1231
#define IDC_PREEXPIRYWARNDAYS           1232
#define IDC_PREWARNEXPIRYSPIN           1233
#define IDC_DEFEXPLORERTREE             1234
#define IDC_DEFENABLEGRIDLINES          1235
#define IDC_COLPICK_GROUP               1236
#define IDC_COLPICK_TITLE               1237
#define IDC_COLPICK_USER                1238
#define IDC_COLPICK_NOTES               1239
#define IDC_COLPICK_PASSWORD            1240
#define IDC_COLPICK_CTIME               1241
#define IDC_COLPICK_PMTIME              1242
#define IDC_COLPICK_ATIME               1243
#define IDC_COLPICK_LTIME               1244
#define IDC_COLPICK_RMTIME              1245
#define IDC_LIST_HEADER                 1246
#define IDC_DEFAULTAUTOTYPE             1247

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         30000
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
