/*
 * Copyright (c) 2003-2016 Rony Shapiro <ronys@pwsafe.org>.
 * All rights reserved. Use of the code is allowed under the
 * Artistic License 2.0 terms, as specified in the LICENSE file
 * distributed with this code, or available from
 * http://www.opensource.org/licenses/artistic-license-2.0.php
 */

#ifndef _VERSION_H_
#define _VERSION_H_

// version.h is automatically generated by cmake from version.cmake
// and the version values in CMakeLists.txt

// Format: Major, Minor, Build, Revision
//   Build  = 0 for all Formally Released versions
//   Build != 0 for all Intermediate versions

#define FILEVER      @pwsafe_at_VERSION_MAJOR@, @pwsafe_at_VERSION_MINOR@, @pwsafe_at_REVISION@
#define PRODUCTVER   @pwsafe_at_VERSION_MAJOR@, @pwsafe_at_VERSION_MINOR@, @pwsafe_at_REVISION@
#define STRATFILEVER "@pwsafe_at_VERSION_MAJOR@, @pwsafe_at_VERSION_MINOR@, @pwsafe_at_REVISION@, @pwsafe_at_VERSTRING@\0"
#define STRATPRODUCTVER  STRATFILEVER

#endif // _VERSION_H_
