#!/bin/sh
# have to use wrapper script, because C::B don't support stream redirection inside `expr`
exec=/usr/bin/32/wx-config
if ! [ -x "$exec" ]; then
exec=wx-config
fi
$exec --version=3.2 "$@" | sed 's/\(^\|\s\)-I/ -isystem /g'
