#!/bin/bash
xdg-icon-resource install --novendor --size 48 --mode system \
                  /usr/share/icons/hicolor/48x48/apps/pwsafe.png
xdg-desktop-menu install --novendor --mode system \
                  /usr/share/applications/passwordsafe.desktop
exit 0
