//{{NO_DEPENDENCIES}}

// Strings
#define DEFAULT_SUFFIX _T("psafe3")
#define SUFFIX_FILTERS _T("Password Safe Databases (*.psafe3; *.dat)|*.psafe3; *.dat|")
#define SUFFIX3_FILTERS _T("Password Safe Databases (*.psafe3)|*.psafe3|")

//  Usage
#define IDS_USAGE                       5000

// Window state
#define IDS_ALWAYSONTOP                 5010

// Status bar
#define IDS_STATCOMPANY                 5020
#define IDS_STATAUTOTYPE                5021
#define IDS_STATBROWSE                  5022
#define IDS_STATCOPYNOTES               5023
#define IDS_STATCOPYPASSWORD            5024
#define IDS_STATCOPYUSERNAME            5025
#define IDS_STATVIEWEDIT                5026
#define IDS_STATCOPYPASSWORDMIN         5027
#define IDS_READ_ONLY                   5028
#define IDS_BLANK                       5029
#define IDS_STATBROWSEPLUS              5030

// File Dailog filters
#define IDS_FDF_V3_ALL                  5050
#define IDS_FDF_DB_ALL                  5051
#define IDS_FDF_DB_BU_ALL               5052
#define IDS_FDF_T_C_ALL                 5053
#define IDS_FDF_X_ALL                   5054
#define IDS_FDF_XML                     5055
#define IDS_FDF_BU                      5056
#define IDS_FDF_BUS                     5057
#define IDS_FDF_PR_ALL                  5058

// Tooltips
#define IDS_RESETPWHISTORYOFF           5100
#define IDS_RESETPWHISTORYON            5101
#define IDS_SETMAXPWHISTORY             5102
#define IDS_REGDEL_CB                   5103
#define IDS_BACKUPBEFORESAVE            5104
#define IDS_USERBACKUPOTHERLOCATION     5106
#define IDS_MAINTAINDATETIMESTAMPS      5107
#define IDS_OTHERBROWSERLOCATION        5108

// Keep DCA together
#define IDS_DCABROWSE                   5191
#define IDS_DCAAUTOTYPE                 5192
#define IDS_DCACOPYNOTES                5193
#define IDS_DCACOPYPASSWORD             5194
#define IDS_DCACOPYUSERNAME             5195
#define IDS_DCAVIEWEDIT                 5196
#define IDS_DCACOPYPASSWORDMIN          5197
#define IDS_DCABROWSEPLUS               5198

// Program strings
#define IDS_LITTLEENDIAN                5207
#define IDS_BIGENDIAN                   5208
#define IDS_ENDIANERROR                 5209
#define IDS_FILEERROR1                  5210
#define IDS_FILEERROR2                  5211
#define IDS_ERRORMESSAGE                5212
#define IDS_FILEREADONLY                5213
#define IDS_FILEPATHNOTFOUND            5214
#define IDS_TERMINATE                   5215
#define IDS_RECENT                      5216
#define IDS_RECENTSAFES                 5217
#define IDS_OPTIONS                     5218
#define IDS_ENCRYPTIONFAILED            5219
#define IDS_GROUPTITLE                  5220
#define IDS_GROUP                       5221
#define IDS_TITLE                       5222
#define IDS_USERNAME                    5223
#define IDS_PASSWORD                    5224
#define IDS_NOTES                       5225
#define IDS_URL                         5226
#define IDS_CREATED                     5227
#define IDS_PASSWORDMODIFIED            5228
#define IDS_LASTACCESSED                5229
#define IDS_PASSWORDEXPIRYDATE          5230
#define IDS_LASTMODIFIED                5232
#define IDS_COPYTITLE                   5233
#define IDS_PROCESSID                   5234
#define IDS_LOCKED                      5235
#define IDS_FILEINUSE                   5236
#define IDS_FILEOPEN                    5237
#define IDS_SAFENOTEXIST                5238
#define IDS_SAVECHANGES                 5239
#define IDS_NUMITEMS                    5240
#define IDS_NEVER                       5241
#define IDS_HIDDENNOTES                 5242
#define IDS_SHOWPASSWORDTXT1            5243
#define IDS_HIDEPASSWORDTXT1            5244
#define IDS_SHOWPASSWORDTXT2            5245
#define IDS_HIDEPASSWORDTXT2            5246
#define IDS_MUSTHAVETITLE               5247
#define IDS_MUSTHAVEPASSWORD            5248
#define IDS_DOTINVALID                  5249
#define IDS_PASSWORDSNOTMATCH           5250
#define IDS_ENTRYEXISTS                 5251
#define IDS_LESS                        5252
#define IDS_MORE                        5253
#define IDS_ENTRIESDONOTMATCH           5254
#define IDS_ENTERKEYANDVERIFY           5255
#define IDS_PASSWORDOVERRIDE            5256
#define IDS_LOCKSAFE                    5257
#define IDS_UNLOCKSAFE                  5258
#define IDS_NOSAFE                      5259
#define IDS_COPYURL                     5260
#define IDS_DATABASEREADONLY            5262
#define IDS_UNKNOWN                     5263
#define IDS_VIEWENTRY                   5264
#define IDS_ON                          5265
#define IDS_OFF                         5266
#define IDS_NEEDDELIMITER               5267
#define IDS_INVALIDDELIMITER            5268
#define IDS_NOFIELDSFOREXPORT           5269
#define IDS_NOOBJECT                    5270
#define IDS_NOFUNCTION                  5271
#define IDS_ENTERSEARCHSTRING           5272
#define IDS_NOMATCHFOUND                5273
#define IDS_FOUNDAMATCH                 5274
#define IDS_FOUNDMATCHES                5275
#define IDS_SEARCHWRAPPED               5276
#define IDS_IMPORTED                    5277
#define IDS_NOCURRENTSAFE               5278
#define IDS_CANNOTBEBLANK               5279
#define IDS_INCORRECTKEY                5280
#define IDS_WEAKPASSPHRASE              5281
#define IDS_USEITANYWAY                 5282
#define IDS_TRYANOTHER                  5283
#define IDS_WRONGOLDPHRASE              5284
#define IDS_CANTVERIFY                  5285
#define IDS_NEWOLDDONOTMATCH            5286
#define IDS_CONFIRMDELETEREG            5287
#define IDS_NOHOTKEY                    5288
#define IDS_INVALIDTIMEOUT              5289
#define IDS_HEXMUTUALLYEXCL             5290
#define IDS_HEXMUSTBEEVEN               5291
#define IDS_MUSTHAVEONEOPTION           5292
#define IDS_DEFAULTPWLENGTH             5293
#define IDS_DEFAULTNUMPWH               5294
#define IDS_SETDATETIME                 5295
#define IDS_TRAYAUTOTYPE                5296
#define IDS_TRAYBROWSE                  5297
#define IDS_TRAYCOPYNOTES               5298
#define IDS_TRAYCOPYPASSWORD            5299
#define IDS_TRAYCOPYUSERNAME            5300
#define IDS_TRAYVIEWEDIT                5301
#define IDS_TRAYDELETETRAYENTRY         5302
#define IDS_CANTPROCESSENTRY            5303
#define IDS_TRAYCOPYURL                 5304
#define IDS_SETUSERNAME                 5305
#define IDS_NEWGROUP                    5306
#define IDS_COPYNUMBER                  5307
#define IDS_COULDNOTSAVE                5308
#define IDS_SAVEERROR                   5309
#define IDS_CANTBROWSE                  5310
#define IDS_CANTOPENSAFE                5311
#define IDS_FILECORRUPT                 5312
#define IDS_FILEREADERROR               5313
#define IDS_SAVEDATABASE                5314
#define IDS_CHOOSEDATABASE              5315
#define IDS_ALREADYOPEN                 5316
#define IDS_OPENDATABASE                5317
#define IDS_CANTOPEN                    5318
#define IDS_FILEOPENERROR               5319
#define IDS_CANTOPENREADING             5320
#define IDS_UNKNOWNERROR                5321
#define IDS_NEWFORMAT                   5322
#define IDS_NEWFORMAT2                  5323
#define IDS_VERSIONWARNING              5324
#define IDS_CANTOPENWRITING             5325
#define IDS_FILEWRITEERROR              5326
#define IDS_NEWNAME1                    5327
#define IDS_NEWNAME2                    5328
#define IDS_FILEISLOCKED                5329
#define IDS_FILELOCKERROR               5330
#define IDS_NAMEEXPORTFILE              5331
#define IDS_NAMETEXTFILE                5332
#define IDS_NAMEXMLFILE                 5333
#define IDS_BADPASSKEY                  5334
#define IDS_PICKTEXTFILE                5335
#define IDS_INVALIDFORMAT               5336
#define IDS_STATUS                      5337
#define IDS_RECORDSIMPORTED             5338
#define IDS_RECORDSNOTREAD              5339
#define IDS_PICKKEEPASSFILE             5340
#define IDS_PICKXMLFILE                 5343
#define IDS_FAILEDXMLVALIDATE           5344
#define IDS_XMLERRORS                   5345
#define IDS_XMLIMPORTWITHERRORS         5346
#define IDS_XMLIMPORTOK                 5347
#define IDS_PICKMERGEFILE               5348
#define IDS_MERGECONFLICTS              5349
#define IDS_MERGINGDATABASE             5350
#define IDS_MERGECOMPLETED              5351
#define IDS_MERGECOMPLETED2             5352
#define IDS_NOCOMPAREFILE               5353
#define IDS_PICKCOMPAREFILE             5354
#define IDS_COMPARESAME                 5355
#define IDS_COMPARESTATISTICS           5356
#define IDS_IDENTICALDATABASES          5357
#define IDS_COMPARECOMPLETE             5358
#define IDS_COMPARESTATS                5359
#define IDS_COMPAREENTRIES1             5360
#define IDS_COMPAREENTRIES2             5361
#define IDS_COMPAREBOTHDIFF             5362
#define IDS_COMPARESTATS2               5363
#define IDS_COMPPASSWORD                5364
#define IDS_COMPNOTES                   5365
#define IDS_COMPURL                     5366
#define IDS_COMPAUTOTYPE                5367
#define IDS_COMPCTIME                   5368
#define IDS_COMPPMTIME                  5369
#define IDS_COMPATIME                   5370
#define IDS_COMPXTIME                   5371
#define IDS_COMPRMTIME                  5372
#define IDS_COMPPWHISTORY               5373
#define IDS_SAVEFIRST                   5374
#define IDS_PICKBACKUP                  5375
#define IDS_PICKRESTORE                 5376
#define IDS_UNTITLEDRESTORE             5377
#define IDS_VALIDATEOK                  5378
#define IDS_FAILEDSAVEPREF              5379
#define IDS_FAILEDSAVEPREFRO            5380
#define IDS_ENTRIESCHANGEDSTOP          5381
#define IDS_ENTRIESCHANGEDSAVE          5382
#define IDS_ENTRIESRESETMAX             5383
#define IDS_SELECTBROWSER               5384
#define IDS_NOIBACKUP                   5385
#define IDS_NONE                        5386
#define IDS_INCREMENTNUM                5387
#define IDS_OPTBACKUPPREF               5388
#define IDS_OPTBACKUPSUBDIR             5389
#define IDS_OPTBACKUPLOCATION           5390
#define IDS_OPTBACKUPNOLOC              5391
#define IDS_OPTBACKUPMAXNUM             5392
#define IDS_OPTBACKUPTITLE              5393
#define IDS_DEFDBNAME                   5394
#define IDS_CREATENAME                  5395
#define IDS_DEMO                        5396
#define IDS_LIMIT_TITLE                 5397
#define IDS_LIMIT_MSG                   5398
#define IDS_LIMIT_MSG2                  5399
#define IDS_MENUEXPCOLGROUP             5400
#define IDS_MENUEDITENTRY               5401
#define IDS_MENUVIEWENTRY               5402
#define IDS_MENUDELETEGROUP             5404
#define IDS_MENURENAMEGROUP             5406
#define IDS_MAXNUMDAYSEXCEEDED          5407
#define IDS_HELPMENU                    5408
#define IDS_U3PURCHASE                  5409
#define IDS_INVALIDEXPIRYWARNDAYS       5410
#define IDS_DRAGNUMBER                  5411
#define IDS_STRICT_LOCKED               5412
#define IDS_CPF_CDD                     5413
#define IDS_NOITEMS                     5414
#define IDS_COMPAREX                    5415
#define IDS_MERGEX                      5416
#define IDS_EXPORT_TEXTX                5417
#define IDS_EXPORT_XMLX                 5418
#define IDS_ENTRYEXISTS2                5419
#define IDS_ADVANCED_TITLETEXT          5420
#define IDS_ADVANCED_PASSWORDTEXT       5421
#define IDS_ADVANCED_GROUPTEXT          5422
#define IDS_ADVANCED_USERTEXT           5423
#define IDS_AUTOTYPE                    5424
#define IDS_PWHISTORY                   5425
#define IDS_ORIGINALDB                  5426
#define IDS_COMPARISONDB                5427
#define IDS_COMPARERESULTS              5428
#define IDS_COPYLEFTRIGHT               5429
#define IDS_ADVANCED_SELECTSOME         5430
#define IDS_ADVANCED_SELECTALL          5431
#define IDS_ADVANCED_DESELECTSOME       5432
#define IDS_ADVANCED_DESELECTALL        5433
#define IDS_NOFIELDSFORCOMPARE          5434
#define IDS_ADVANCED                    5435
#define IDS_UNKNOWNFIELDS               5436
#define IDS_YES                         5437
#define IDS_NO                          5438
#define IDS_XMLUNKNFLDIGNORED           5439
#define IDS_XMLIMPORTFAILED             5440
#define IDS_COPYUNKNOWNFIELDS           5441
#define IDS_FINDX                       5442
#define IDS_NOFIELDSFORSEARCH           5443
#define IDS_NUMCHILD                    5444
#define IDS_NUMCHILDREN                 5445
#define IDS_DELENT                      5446
#define IDS_EXTERNAL_EDITOR_WARNING     5447
#define IDS_NOTES_IN_EXTERNAL_EDITOR    5448
#define IDS_CPF_TVDD                    5449
#define IDS_RECORDUNKNOWNFIELDS         5450
#define IDS_IMPORTFILE                  5451
#define IDS_VIEWDEPENDENTS              5452
#define IDS_DELETEABASE                 5453
#define IDS_DELETEBASET                 5454
#define IDS_ALIASNOTFOUNDA              5455
#define IDS_ALIASNOTFOUND0A             5456
#define IDS_ALIASNOTFOUND0B             5457
#define IDS_ALIASNOTFOUND1A             5458
#define IDS_ALIASNOTFOUND1B             5459
#define IDS_ALIASNOTFOUND2A             5460
#define IDS_ALIASNOTFOUND2B             5461
#define IDS_ALIASNOTFOUND2C             5462
#define IDS_ALIASNOTFOUNDZ              5463
#define IDS_DDBASEISALIAS               5464
#define IDS_BASEISALIAS                 5465
#define IDS_ALIASCANTREFERTOITSELF      5466
#define IDS_BASEHASNOTITLE              5467
#define IDS_CLOSE_B4_CHECK              5468
#define IDS_CONFIRM_CLOSE               5469
#define IDS_LATEST_VERSION              5470
#define IDS_CANT_CONTACT_SERVER         5471
#define IDS_UP2DATE                     5472
#define IDS_NEWER_AVAILABLE_SHORT       5473
#define IDS_CANT_READ_VERINFO           5474
#define IDS_TRYING2CONTACT_SERVER       5475
#define IDS_NEWER_CAPTION               5476
#define IDS_NEWER_AVAILABLE             5477
#define IDS_NEWER_AVAILABLE_U3          5478
#define IDS_TEXTIMPORTFAILED            5479
#define IDS_COMPARINGDATABASE           5480
#define IDS_COPYENTRY                   5481
#define IDS_CASE_INSENSITIVE            5482
#define IDS_CASE_SENSITIVE              5483
#define IDS_CANTEMAIL                   5484
#define IDS_MENUSENDEMAIL               5486
#define IDS_SELECTREPORT                5487
#define IDS_NOREPORTSEXIST              5488
#define IDS_VISIT_WEBSITE               5489
#define IDS_ENTRY                       5490
#define IDS_ENTRIES                     5491
#define IDS_ALIAS                       5492
#define IDS_ALIASES                     5493
#define IDS_CONFLICT                    5494
#define IDS_CONFLICTS                   5495
#define IDS_ICON                        5496
#define IDS_SHORTCUT                    5497
#define IDS_SHORTCUTS                   5498
#define IDS_ABASEINVALID                5499
#define IDS_SBASEINVALID                5500
#define IDS_MUSTHAVETARGET              5501
#define IDS_VIEWSHORTCUTS               5502
#define IDS_VIEWALIASESBTN              5503
#define IDS_VIEWSHORTCUTSBTN            5504
#define IDS_MULTIPLETARGETSFOUND        5505
#define IDS_TARGETNOTFOUND              5506
#define IDS_PROVISMUTUALLYEXCL          5507
#define IDS_PWPOLICY                    5508
#define IDS_COMPPWPOLICY                5509
#define IDS_SETPASSWORDPOLICY           5510
#define IDS_DEFAULTPWLENGTHTOOSMALL     5511
#define IDS_CANTSPECIFYMINNUMBER        5512
#define IDS_SAMPLETEXT                  5513
#define IDS_EMPTYSAMPLETEXT             5514
#define IDS_MENUCOPYEMAIL               5516
#define IDS_COPYEMAIL                   5517
#define IDS_DELETESBASE                 5518
#define IDS_SHORTCUTEXPLANATION         5519
#define IDS_SCTARGET                    5520
#define IDS_SAVEBEFOREEXPORT            5521
#define IDS_ADVANCEDOPTIONS             5522
#define IDS_ADVANCEDSUBSET              5523
#define IDS_ADVCASE_INSENSITIVE         5524
#define IDS_ADVCASE_SENSITIVE           5525
#define IDS_ADVANCEDFIELDS              5526
#define IDS_USER                        5528
#define IDS_PSWD                        5529
#define IDS_SHOWTOOLBAR                 5530
#define IDS_HIDETOOLBAR                 5531
#define IDS_RPTCOMPARE                  5532
#define IDS_RPTFIND                     5533
#define IDS_RPTIMPORTTEXT               5534
#define IDS_RPTIMPORTXML                5535
#define IDS_RPTMERGE                    5536
#define IDS_RPTVALIDATE                 5537
#define IDS_SEARCHRESULTS1              5538
#define IDS_SEARCHRESULTS2              5539
#define IDS_REPORTCREATED               5540
#define IDS_FINDGROUP                   5541
#define IDS_FINDTITLE                   5542
#define IDS_FINDUSER                    5543
#define IDS_TEXT                        5544
#define IDS_XML                         5545
#define IDS_VIEWREPORT                  5546
#define IDS_CANCEL                      5547
#define IDS_CONTINUE                    5548
#define IDS_EXIT                        5549
#define IDS_READONLY                    5550
#define IDS_READWRITE                   5551
#define IDS_SEARCH                      5552
#define IDS_NEW                         5553
#define IDS_IN_N_DAYS                   5554
#define IDS_OVERRIDE_POLICY             5555
#define IDS_PASSWORDEXPIRYDATEINT       5556
#define IDS_NOFIELDSFORFILTER           5557
#define IDS_NUMTOOSMALL                 5558
#define IDS_NUMTOOLARGE                 5559
#define IDS_NUM1NEGATIVE                5560
#define IDS_NUM1NOTLTNUM2               5561
#define IDS_CANTBELESSTHANMIN           5562
#define IDS_CANTBEGREATERTHANMAX        5563
#define IDS_NUM1CANTBEMAX               5564
#define IDS_DATE1NOTB4DATE2             5565
#define IDS_NOSTRING                    5566
#define IDS_FILTERINCOMPLETE            5567
#define IDS_NOFILTERSENABLED            5568
#define IDS_NORULESELECTED              5569
#define IDS_ENTRYTYPE                   5570
#define IDS_FILTERINFO_NONE             5571
#define IDS_FILTERINFO                  5572
#define IDS_HFILTERINFO                 5573
#define IDS_PFILTERINFO                 5574
#define IDS_PRESENT                     5575
#define IDS_HACTIVE                     5576
#define IDS_HNUM                        5577
#define IDS_HMAX                        5578
#define IDS_HDATE                       5579
#define IDS_HPSWD                       5580
#define IDS_PLENGTH                     5581
#define IDS_PLOWER                      5582
#define IDS_PUPPER                      5583
#define IDS_PDIGITS                     5584
#define IDS_PSYMBOL                     5585
#define IDS_PEASYVISION                 5586
#define IDS_PPRONOUNCEABLE              5587
#define IDS_PHEXADECIMAL                5588
#define IDS_PASSWORDHISTORY             5589
#define IDS_UNKNOWNFIELDSFILTER         5590
#define IDS_FILTERACTIVE                5594
#define IDS_FILTERINACTIVE              5595
#define IDS_FILTERFIELD                 5596
#define IDS_FILTERRULE                  5597
#define IDS_NOITEMSPASSEDFILTERING      5600
#define IDS_NOTDEFINED                  5601
#define IDS_SETDISPLAYFILTERS           5602
#define IDS_SETPWHISTFILTERS            5603
#define IDS_SETPWPOLICYFILTER           5604
#define IDS_SETFILTERS                  5605
#define IDS_CLEARFILTERS                5606
#define IDS_HELP                        5607
#define IDS_OK                          5608
#define IDS_NUMITEMSFILTER              5609
#define IDS_AND_OR                      5610
#define IDS_SELECTFIELD                 5611
#define IDS_CRITERIA_DESC               5612
#define IDS_PICKFIELD                   5613
#define IDS_FLC_TOOLTIP0                5614
#define IDS_FLC_TOOLTIP1                5615
#define IDS_FLC_TOOLTIP2                5616
#define IDS_FLC_TOOLTIP3                5617
#define IDS_FLC_TOOLTIP4                5618
#define IDS_FLC_TOOLTIP5                5619
#define IDS_FLC_TOOLTIP6                5620
#define IDS_FILTERNAMEEMPTY             5621
#define IDS_DELETE                      5622
#define IDS_SELECT                      5623
#define IDS_VIEW                        5624
#define IDS_FILTERSEXPORTEDOK           5625
#define IDS_FILTERSIMPORTEDOK           5626
#define IDS_SELECTFROMSTORE             5627
#define IDS_DELETEFROMSTORE             5628
#define IDS_VIEWFROMSTORE               5629
#define IDS_CANTAUTOIMPORTFILTERS       5630
#define IDS_REPLACEFILTER               5631
#define IDS_FILTEREXISTS                5632
#define IDS_SHOWDRAGBAR                 5633
#define IDS_HIDEDRAGBAR                 5634
#define IDS_CONFIRMFILTERDELETE         5635
#define IDS_DBPOOLNAME                  5636
#define IDS_AUTOLOADPOOLNAME            5637
#define IDS_IMPORTEDPOOLNAME            5638
#define IDS_SESSIONPOOLNAME             5639
#define IDS_FILTERNAME                  5640
#define IDS_FILTERSOURCE                5641
#define IDS_FILTERCOPY2DB               5642
#define IDS_FILTEREXPORT                5643
#define IDS_FILTERAPPLY                 5644
#define IDS_MINIMIZECONFLICT            5645
#define IDS_CLICKTOCOPY                 5646
#define IDS_SUBSETINDEXZERO             5647
#define IDS_SUBSETINDEXTOOBIG           5648
#define IDS_MENUCREATESHORTCUT          5649
#define IDS_AREYOUSURE                  5650
#define IDS_EDITEXTERNALLY              5651
#define IDS_WORD_WRAP                   5652
#define IDS_SHOW_NOTES                  5653
#define IDS_RUNCOMMAND                  5654
#define IDS_COMPRUNCOMMAND              5655
#define IDS_TRAYRUNCOMMAND              5656
#define IDS_CANTRUNCOMMAND              5657
#define IDS_CLICKTOCOPYEXPAND           5658
#define IDS_RUNCOMMAND_ERROR            5659
#define IDS_CANTLOAD_AUTOTYPEDLL        5660
#define IDS_RUN_ERRORMSG                5661
#define IDS_RUN_IGNOREORFIX             5662
#define IDS_SEARCHTOP                   5663
#define IDS_SEARCHBOTTOM                5665
#define IDS_TRAYBROWSEPLUS              5666
#define IDS_LAUNCH                      5667
#define IDS_LAUNCHPLUS                  5668
#define IDS_CLICKTOGOPLUS               5669
#define IDS_DELGRP                      5670
#define IDS_GROUPCOPIED                 5671
#define IDS_TITLECOPIED                 5672
#define IDS_USERCOPIED                  5673
#define IDS_PSWDCOPIED                  5674
#define IDS_NOTESCOPIED                 5675
#define IDS_URLCOPIED                   5676
#define IDS_AUTOTYPECOPIED              5677
#define IDS_RUNCMDCOPIED                5678
#define IDS_COL_MENUITEM                5680
#define IDS_COL_SHORTCUT                5681
#define IDS_SHCT_TOOLTIP0               5682
#define IDS_SHCT_TOOLTIP1               5683
#define IDS_SHCT_WARNING1               5684
#define IDS_SHCT_WARNING2               5685
#define IDS_SHCT_WARNING3               5686
#define IDS_CTRLP                       5687
#define IDS_ALTP                        5688
#define IDS_SHIFTP                      5689
#define IDS_OSK_VERSION_MISMATCH        5690
#define IDS_COMPXTIME_INT               5691
#define IDS_TREEFONT                    5692
#define IDS_PSWDFONT                    5693
#define IDS_OSK_NO_UNICODE_FONT         5694
