
//

#include "StdAfx.h"

#include "Fonts.h"

#include <vector>

std::vector<std::wstring> vsInstalledFonts;

Fonts_Index DefaultFontIndex[] = {
  { /*   0 */   FONT_NOT_INSTALLED, L"Aboriginal Serif"},
  { /*   1 */   FONT_NOT_INSTALLED, L"Abyssinica SIL"},
  { /*   2 */   FONT_NOT_INSTALLED, L"Aegean"},
  { /*   3 */   FONT_NOT_INSTALLED, L"Aegyptus"},
  { /*   4 */   FONT_NOT_INSTALLED, L"Ahuramazda"},
  { /*   5 */   FONT_NOT_INSTALLED, L"Akkadian"},
  { /*   6 */   FONT_NOT_INSTALLED, L"Aksara Bali"},
  { /*   7 */   FONT_NOT_INSTALLED, L"Amiri"},
  { /*   8 */   FONT_NOT_INSTALLED, L"Analecta"},
  { /*   9 */   FONT_NOT_INSTALLED, L"Antinoou"},
  { /*  10 */   FONT_NOT_INSTALLED, L"Aparajita"},
  { /*  11 */   FONT_NOT_INSTALLED, L"Arabic Typesetting"},
  { /*  12 */   FONT_NOT_INSTALLED, L"Aramaic Imperial Yeb"},
  { /*  13 */   FONT_NOT_INSTALLED, L"Arial Unicode MS"},
  { /*  14 */   FONT_NOT_INSTALLED, L"Asea"},
  { /*  15 */   FONT_NOT_INSTALLED, L"BabelStone Han"},
  { /*  16 */   FONT_NOT_INSTALLED, L"BabelStone Phags-pa Book"},
  { /*  17 */   FONT_NOT_INSTALLED, L"Batak-Unicode"},
  { /*  18 */   FONT_NOT_INSTALLED, L"Batang"},
  { /*  19 */   FONT_NOT_INSTALLED, L"Cambria"},
  { /*  20 */   FONT_NOT_INSTALLED, L"Cambria Math"},
  { /*  21 */   FONT_NOT_INSTALLED, L"Charis SIL"},
  { /*  22 */   FONT_NOT_INSTALLED, L"Code2000"},
  { /*  23 */   FONT_NOT_INSTALLED, L"Code2001"},
  { /*  24 */   FONT_NOT_INSTALLED, L"Conakry"},
  { /*  25 */   FONT_NOT_INSTALLED, L"Dai Banna SIL Book"},
  { /*  26 */   FONT_NOT_INSTALLED, L"DokChampa"},
  { /*  27 */   FONT_NOT_INSTALLED, L"Dotum"},
  { /*  28 */   FONT_NOT_INSTALLED, L"Doulos SIL"},
  { /*  29 */   FONT_NOT_INSTALLED, L"Dukor"},
  { /*  30 */   FONT_NOT_INSTALLED, L"Ebrima"},
  { /*  31 */   FONT_NOT_INSTALLED, L"Eeyek Unicode"},
  { /*  32 */   FONT_NOT_INSTALLED, L"Estrangelo Edessa"},
  { /*  33 */   FONT_NOT_INSTALLED, L"Euphemia"},
  { /*  34 */   FONT_NOT_INSTALLED, L"Everson Mono"},
  { /*  35 */   FONT_NOT_INSTALLED, L"Ezra SIL"},
  { /*  36 */   FONT_NOT_INSTALLED, L"Gardiner"},
  { /*  37 */   FONT_NOT_INSTALLED, L"Gautami"},
  { /*  38 */   FONT_NOT_INSTALLED, L"Gentium Plus"},
  { /*  39 */   FONT_NOT_INSTALLED, L"Gulim"},
  { /*  40 */   FONT_NOT_INSTALLED, L"HAN NOM A"},
  { /*  41 */   FONT_NOT_INSTALLED, L"HAN NOM B"},
  { /*  42 */   FONT_NOT_INSTALLED, L"HanaMin"},
  { /*  43 */   FONT_NOT_INSTALLED, L"Iskoola Pota"},
  { /*  44 */   FONT_NOT_INSTALLED, L"Kalinga"},
  { /*  45 */   FONT_NOT_INSTALLED, L"Kartika"},
  { /*  46 */   FONT_NOT_INSTALLED, L"Khmer Busra"},
  { /*  47 */   FONT_NOT_INSTALLED, L"KhojkiUnicodeOT"},
  { /*  48 */   FONT_NOT_INSTALLED, L"Lanna Alif"},
  { /*  49 */   FONT_NOT_INSTALLED, L"Latha"},
  { /*  50 */   FONT_NOT_INSTALLED, L"Lisu Unicode"},
  { /*  51 */   FONT_NOT_INSTALLED, L"Mangal"},
  { /*  52 */   FONT_NOT_INSTALLED, L"Meiryo"},
  { /*  53 */   FONT_NOT_INSTALLED, L"Miao Unicode"},
  { /*  54 */   FONT_NOT_INSTALLED, L"Microsoft Himalaya"},
  { /*  55 */   FONT_NOT_INSTALLED, L"Microsoft JhengHei"},
  { /*  56 */   FONT_NOT_INSTALLED, L"Microsoft New Tai Lue"},
  { /*  57 */   FONT_NOT_INSTALLED, L"Microsoft PhagsPa"},
  { /*  58 */   FONT_NOT_INSTALLED, L"Microsoft Tai Le"},
  { /*  59 */   FONT_NOT_INSTALLED, L"Microsoft Uighur"},
  { /*  60 */   FONT_NOT_INSTALLED, L"Microsoft YaHei"},
  { /*  61 */   FONT_NOT_INSTALLED, L"Microsoft Yi Baiti"},
  { /*  62 */   FONT_NOT_INSTALLED, L"MingLiU"},
  { /*  63 */   FONT_NOT_INSTALLED, L"MingLiU_HKSCS-ExtB"},
  { /*  64 */   FONT_NOT_INSTALLED, L"MingLiU-ExtB"},
  { /*  65 */   FONT_NOT_INSTALLED, L"Mingzat"},
  { /*  66 */   FONT_NOT_INSTALLED, L"Mongolian Baiti"},
  { /*  67 */   FONT_NOT_INSTALLED, L"MoolBoran"},
  { /*  68 */   FONT_NOT_INSTALLED, L"Mro Unicode"},
  { /*  69 */   FONT_NOT_INSTALLED, L"Musica"},
  { /*  70 */   FONT_NOT_INSTALLED, L"MV Boli"},
  { /*  71 */   FONT_NOT_INSTALLED, L"Namdhinggo SIL"},
  { /*  72 */   FONT_NOT_INSTALLED, L"New Athena Unicode"},
  { /*  73 */   FONT_NOT_INSTALLED, L"Nilus"},
  { /*  74 */   FONT_NOT_INSTALLED, L"Nirmala UI"},
  { /*  75 */   FONT_NOT_INSTALLED, L"Noto Kufi Arabic"},
  { /*  76 */   FONT_NOT_INSTALLED, L"Noto Naskh Arabic"},
  { /*  77 */   FONT_NOT_INSTALLED, L"Noto Sans Armenian"},
  { /*  78 */   FONT_NOT_INSTALLED, L"Noto Sans Avestan"},
  { /*  79 */   FONT_NOT_INSTALLED, L"Noto Sans Balinese"},
  { /*  80 */   FONT_NOT_INSTALLED, L"Noto Sans Bamum"},
  { /*  81 */   FONT_NOT_INSTALLED, L"Noto Sans Batak"},
  { /*  82 */   FONT_NOT_INSTALLED, L"Noto Sans Bengali"},
  { /*  83 */   FONT_NOT_INSTALLED, L"Noto Sans Brahmi"},
  { /*  84 */   FONT_NOT_INSTALLED, L"Noto Sans Buginese"},
  { /*  85 */   FONT_NOT_INSTALLED, L"Noto Sans Buhid"},
  { /*  86 */   FONT_NOT_INSTALLED, L"Noto Sans Canadian Aboriginal"},
  { /*  87 */   FONT_NOT_INSTALLED, L"Noto Sans Carian"},
  { /*  88 */   FONT_NOT_INSTALLED, L"Noto Sans Cham"},
  { /*  89 */   FONT_NOT_INSTALLED, L"Noto Sans Cherokee"},
  { /*  90 */   FONT_NOT_INSTALLED, L"Noto Sans Coptic"},
  { /*  91 */   FONT_NOT_INSTALLED, L"Noto Sans Cuneiform"},
  { /*  92 */   FONT_NOT_INSTALLED, L"Noto Sans Cypriot"},
  { /*  93 */   FONT_NOT_INSTALLED, L"Noto Sans Deseret"},
  { /*  94 */   FONT_NOT_INSTALLED, L"Noto Sans Devanagari"},
  { /*  95 */   FONT_NOT_INSTALLED, L"Noto Sans Egyptian Hieroglyphs"},
  { /*  96 */   FONT_NOT_INSTALLED, L"Noto Sans Ethiopic"},
  { /*  97 */   FONT_NOT_INSTALLED, L"Noto Sans Georgian"},
  { /*  98 */   FONT_NOT_INSTALLED, L"Noto Sans Glagolitic"},
  { /*  99 */   FONT_NOT_INSTALLED, L"Noto Sans Gothic"},
  { /* 100 */   FONT_NOT_INSTALLED, L"Noto Sans Gujarati"},
  { /* 101 */   FONT_NOT_INSTALLED, L"Noto Sans Gurmukhi"},
  { /* 102 */   FONT_NOT_INSTALLED, L"Noto Sans Hanunoo"},
  { /* 103 */   FONT_NOT_INSTALLED, L"Noto Sans Hebrew"},
  { /* 104 */   FONT_NOT_INSTALLED, L"Noto Sans Imperial Aramaic"},
  { /* 105 */   FONT_NOT_INSTALLED, L"Noto Sans Inscriptional Pahlavi"},
  { /* 106 */   FONT_NOT_INSTALLED, L"Noto Sans Inscriptional Parthian"},
  { /* 107 */   FONT_NOT_INSTALLED, L"Noto Sans Javanese"},
  { /* 108 */   FONT_NOT_INSTALLED, L"Noto Sans Kaithi"},
  { /* 109 */   FONT_NOT_INSTALLED, L"Noto Sans Kannada"},
  { /* 110 */   FONT_NOT_INSTALLED, L"Noto Sans Kayah Li"},
  { /* 111 */   FONT_NOT_INSTALLED, L"Noto Sans Kharoshthi"},
  { /* 112 */   FONT_NOT_INSTALLED, L"Noto Sans Khmer"},
  { /* 113 */   FONT_NOT_INSTALLED, L"Noto Sans Korean"},
  { /* 114 */   FONT_NOT_INSTALLED, L"Noto Sans Lao"},
  { /* 115 */   FONT_NOT_INSTALLED, L"Noto Sans Lepcha"},
  { /* 116 */   FONT_NOT_INSTALLED, L"Noto Sans Limbu"},
  { /* 117 */   FONT_NOT_INSTALLED, L"Noto Sans Linear B"},
  { /* 118 */   FONT_NOT_INSTALLED, L"Noto Sans Lisu"},
  { /* 119 */   FONT_NOT_INSTALLED, L"Noto Sans Lycian"},
  { /* 120 */   FONT_NOT_INSTALLED, L"Noto Sans Lydian"},
  { /* 121 */   FONT_NOT_INSTALLED, L"Noto Sans Malayalam"},
  { /* 122 */   FONT_NOT_INSTALLED, L"Noto Sans Mandaic"},
  { /* 123 */   FONT_NOT_INSTALLED, L"Noto Sans Meetei Mayek"},
  { /* 124 */   FONT_NOT_INSTALLED, L"Noto Sans Mongolian"},
  { /* 125 */   FONT_NOT_INSTALLED, L"Noto Sans Myanmar"},
  { /* 126 */   FONT_NOT_INSTALLED, L"Noto Sans New Tai Lue"},
  { /* 127 */   FONT_NOT_INSTALLED, L"Noto Sans NKO"},
  { /* 128 */   FONT_NOT_INSTALLED, L"Noto Sans Ogham"},
  { /* 129 */   FONT_NOT_INSTALLED, L"Noto Sans Ol Chiki"},
  { /* 130 */   FONT_NOT_INSTALLED, L"Noto Sans Old Italic"},
  { /* 131 */   FONT_NOT_INSTALLED, L"Noto Sans Old Persian"},
  { /* 132 */   FONT_NOT_INSTALLED, L"Noto Sans Old South Arabian"},
  { /* 133 */   FONT_NOT_INSTALLED, L"Noto Sans Old Turkic"},
  { /* 134 */   FONT_NOT_INSTALLED, L"Noto Sans Oriya"},
  { /* 135 */   FONT_NOT_INSTALLED, L"Noto Sans Osmanya"},
  { /* 136 */   FONT_NOT_INSTALLED, L"Noto Sans Phags Pa"},
  { /* 137 */   FONT_NOT_INSTALLED, L"Noto Sans Phags-pa"},
  { /* 138 */   FONT_NOT_INSTALLED, L"Noto Sans Phoenician"},
  { /* 139 */   FONT_NOT_INSTALLED, L"Noto Sans Rejang"},
  { /* 140 */   FONT_NOT_INSTALLED, L"Noto Sans Runic"},
  { /* 141 */   FONT_NOT_INSTALLED, L"Noto Sans Samaritan"},
  { /* 142 */   FONT_NOT_INSTALLED, L"Noto Sans Saurashtra"},
  { /* 143 */   FONT_NOT_INSTALLED, L"Noto Sans Shavian"},
  { /* 144 */   FONT_NOT_INSTALLED, L"Noto Sans Sinhala"},
  { /* 145 */   FONT_NOT_INSTALLED, L"Noto Sans Sumero-Akkadian Cuneiform"},
  { /* 146 */   FONT_NOT_INSTALLED, L"Noto Sans Sundanese"},
  { /* 147 */   FONT_NOT_INSTALLED, L"Noto Sans Syloti Nagri"},
  { /* 148 */   FONT_NOT_INSTALLED, L"Noto Sans Symbols"},
  { /* 149 */   FONT_NOT_INSTALLED, L"Noto Sans Syriac Eastern"},
  { /* 150 */   FONT_NOT_INSTALLED, L"Noto Sans Syriac Estrangela"},
  { /* 151 */   FONT_NOT_INSTALLED, L"Noto Sans Syriac Western"},
  { /* 152 */   FONT_NOT_INSTALLED, L"Noto Sans Tagalog"},
  { /* 153 */   FONT_NOT_INSTALLED, L"Noto Sans Tagbanwa"},
  { /* 154 */   FONT_NOT_INSTALLED, L"Noto Sans Tai Le"},
  { /* 155 */   FONT_NOT_INSTALLED, L"Noto Sans Tai Tham"},
  { /* 156 */   FONT_NOT_INSTALLED, L"Noto Sans Tai Viet"},
  { /* 157 */   FONT_NOT_INSTALLED, L"Noto Sans Tamil"},
  { /* 158 */   FONT_NOT_INSTALLED, L"Noto Sans Telugu"},
  { /* 159 */   FONT_NOT_INSTALLED, L"Noto Sans Thai"},
  { /* 160 */   FONT_NOT_INSTALLED, L"Noto Sans Tifinagh"},
  { /* 161 */   FONT_NOT_INSTALLED, L"Noto Sans Ugaritic"},
  { /* 162 */   FONT_NOT_INSTALLED, L"Noto Sans Vai"},
  { /* 163 */   FONT_NOT_INSTALLED, L"Noto Sans Yi"},
  { /* 164 */   FONT_NOT_INSTALLED, L"Noto Serif Armenian"},
  { /* 165 */   FONT_NOT_INSTALLED, L"Noto Serif Georgian"},
  { /* 166 */   FONT_NOT_INSTALLED, L"Noto Serif Khmer"},
  { /* 167 */   FONT_NOT_INSTALLED, L"Noto Serif Lao"},
  { /* 168 */   FONT_NOT_INSTALLED, L"Noto Serif Thai"},
  { /* 169 */   FONT_NOT_INSTALLED, L"Nuosu SIL"},
  { /* 170 */   FONT_NOT_INSTALLED, L"Nyala"},
  { /* 171 */   FONT_NOT_INSTALLED, L"Padauk"},
  { /* 172 */   FONT_NOT_INSTALLED, L"Plantagenet Cherokee"},
  { /* 173 */   FONT_NOT_INSTALLED, L"Quivira"},
  { /* 174 */   FONT_NOT_INSTALLED, L"Raavi"},
  { /* 175 */   FONT_NOT_INSTALLED, L"RibengUni"},
  { /* 176 */   FONT_NOT_INSTALLED, L"Sadagolthina"},
  { /* 177 */   FONT_NOT_INSTALLED, L"Scheherazade"},
  { /* 178 */   FONT_NOT_INSTALLED, L"Segoe UI Historic"},
  { /* 179 */   FONT_NOT_INSTALLED, L"Segoe UI Symbol"},
  { /* 180 */   FONT_NOT_INSTALLED, L"Shruti"},
  { /* 181 */   FONT_NOT_INSTALLED, L"Siddhanta"},
  { /* 182 */   FONT_NOT_INSTALLED, L"SIL Yi"},
  { /* 183 */   FONT_NOT_INSTALLED, L"Source Han Sans"},
  { /* 184 */   FONT_NOT_INSTALLED, L"Source Han Sans KR"},
  { /* 185 */   FONT_NOT_INSTALLED, L"Sundanese Unicode"},
  { /* 186 */   FONT_NOT_INSTALLED, L"Sylfaen"},
  { /* 187 */   FONT_NOT_INSTALLED, L"Symbola"},
  { /* 188 */   FONT_NOT_INSTALLED, L"Tai Heritage Pro"},
  { /* 189 */   FONT_NOT_INSTALLED, L"Tibetan Machine Uni"},
  { /* 190 */   FONT_NOT_INSTALLED, L"Times New Roman"},
  { /* 191 */   FONT_NOT_INSTALLED, L"Traditional Arabic"},
  { /* 192 */   FONT_NOT_INSTALLED, L"Tuladha Jejeg"},
  { /* 193 */   FONT_NOT_INSTALLED, L"Tunga"},
  { /* 194 */   FONT_NOT_INSTALLED, L"UnBatang"},
  { /* 195 */   FONT_NOT_INSTALLED, L"Vani"},
  { /* 196 */   FONT_NOT_INSTALLED, L"Vijaya"},
  { /* 197 */   FONT_NOT_INSTALLED, L"Virinda"},
  { /* 198 */   FONT_NOT_INSTALLED, L"Wakor"},
  { /* 199 */   FONT_NOT_INSTALLED, L"ZH Mono"},
};
