.\" Process this file with
.\" groff -man -Tascii pwsafe.1
.\"
.TH PWSAFE 1 "JULY 2010" Linux "User Manuals"
.SH NAME
pwsafe \- Secure Password Manager
.SH SYNOPSIS
.B pwsafe [-g
.I config-file
.B ] [-u
.I user
.B ] [ -h
.I host
.B ]
.B [-r]
.B [
.I database
.B ]
pwsafe
.B -v database
pwsafe
.B [-e|-d] file
pwsafe
.B [-c|-s|-m]
.SH DESCRIPTION
.B pwsafe
manages your passwords in a convenient yet secure manner.
.SH OPTIONS
.IP -b
Do not write `busy' to stdout while processing.
.IP "-c config-file"
Use the alternate system wide
.I config-file
instead of
.IR /etc/foo.conf .
This overrides any
.B FOOCONF
environment variable.
.IP -a
In addition to the baz segments, also parse the
blurfl headers.
.IP -r
Recursive mode. Operates as fast as lightning
at the expense of a megabyte of virtual memory.
.SH FILES
.I /etc/foo.conf
.RS
The system wide configuration file. See
.BR foo (5)
for further details.
.RE
.I ~/.foorc
.RS
Per user configuration file. See
.BR foo (5)
for further details.
.SH ENVIRONMENT
.IP FOOCONF
If non-null the full pathname for an alternate system wide
.IR foo.conf .
Overridden by the
.B -c
option.
.SH DIAGNOSTICS
The following diagnostics may be issued on stderr:
 
Bad magic number.
.RS
The input file does not look like an archive file.
.RE
Old style baz segments.
.RS
.B foo
can only handle new style baz segments.
.SH BUGS
This man page is little more than a placeholder (yet).
.SH AUTHOR
Rony Shapiro <ronys at sf dot net>

